### ISSUE TITLE
Seamless connection issue with galaxy buds

### ISSUE THREAD

**Issue by Prajwalmegalamani** [ThePBone/GalaxyBudsClient#10]
In the before version of the app it was easily connecting to my PC by disconnecting it my phone when i hit connect button,
but not connect button seems to disconnect from my phone but buds don't connect to the PC. 
(Maybe a windows issue: Windows update build 2004)
Please check this up and clear it out

**Comment by ThePBone** [comment]
Is 'Seamless Connection' enabled?
If it is and it still doesn't want to connect without disconnecting it from the other device first, then this is probably a problem of your Bluetooth or Windows driver. This app doesn't handle the actual connection stuff, that is normally handled by the driver.

**Comment by Prajwalmegalamani** [comment]
Yes it's enabled i guess it's an issue with my drivers i guess!
