### ISSUE TITLE
[UI Fix] Touchpad > Voice Asisstant (Android only)

### ISSUE THREAD

**Issue by ArthurWolfhound** [ThePBone/GalaxyBudsClient#11]
Hi! It is **not** really a bug or issue, just the fact that Cortana actually starts listening from assigned touchpad action, so you might need to remove "(Android only)" from touchpad command for Voice Assistant, can't say anything about Mac though, don't have any...

Windows 10 Home with language set to English (United States) so I do have Cortana enabled. No fixes or mods to get this functionality.

Thanks a lot for this wonderful piece of software!

**Comment by ThePBone** [comment]
Wow, I didn't expect that to work. I have Cortana disabled so couldn't verify it before.

These commits rename the entry:
b0a89b015b06c7a63436e98950d8ada93c154e9d
d26a018ffdb7a7aec9522f3259b0e5a14bd802d9

Thanks for mentioning it!
