### ISSUE TITLE
[REQ] What would be needed to port it to macOS?

### ISSUE THREAD

**Issue by MisterTechnik** [ThePBone/GalaxyBudsClient#115]
I know you said you personally wouldn’t make a port for macOS.

But what exactly would be needed to change/add in order to make it mac compatible?

I highly doubt it, but if it doesn’t require advanced .net skills, I might be able to look into this.
Thought it would probably also be helpful for others interested in porting it to macOS.

**Comment by ThePBone** [comment]
The UI portion should run without any issues, but someone would need to re-implement interfaces for platform-specific services:

* **Bluetooth backend** ([IBluetoothService](https://github.com/ThePBone/GalaxyBudsClient/blob/master/GalaxyBudsClient.Bluetooth/IBluetoothService.cs))
* Tray icon implementation ([ITrayIcon](https://github.com/ThePBone/GalaxyBudsClient/blob/master/GalaxyBudsClient.Interop.TrayIcon/ITrayIcon.cs))
* Auto-start management ([IAutoStartHelper](https://github.com/ThePBone/GalaxyBudsClient/blob/master/GalaxyBudsClient/Platform/Interfaces/IAutoStartHelper.cs))
* Global play/pause media key events ([IMediaKeyRemote](https://github.com/ThePBone/GalaxyBudsClient/blob/master/GalaxyBudsClient/Platform/Interfaces/IMediaKeyRemote.cs))
* Custom touch action "Press Hotkey" ([IHotkeyBroadcast](https://github.com/ThePBone/GalaxyBudsClient/blob/master/GalaxyBudsClient/Platform/Interfaces/IHotkeyBroadcast.cs))
* Global customizable keyboard hotkeys ([IHotkeyReceiver](https://github.com/ThePBone/GalaxyBudsClient/blob/master/GalaxyBudsClient/Platform/Interfaces/IHotkeyReceiver.cs))

I linked every interface definition above, so you can see exactly which feature requires which functions.

From all of these interfaces, only the `IBluetoothService` one is mandatory. You can leave out the others, but the app would run with a significantly reduced feature-set.

**Comment by incheon-kim** [comment]
To simulate global keyboard press(also media events), dynamic library built from swift code or Xamarin.Mac is the best way to do it.
But Xamarin.Mac is way too heavy for this project because its dll file is almost 25MB.
Implementing via Swift and Appkit would be lighter than Xamarin.Mac. It still needs to be built separately from this project.

**Comment by ThePBone** [comment]
I'm now working on this since I grabbed a very cheap old MacBook Pro 2011 from eBay for other purposes.
I can't provide an ETA right now; I'm only working on this every now and then.

While the GUI code is already stable, the native implementations for the modules mentioned above are still missing. For these native implementations, I'm creating a separate dynamic library written in Objective-C++ with a C wrapper for easy integration into the main C# code. 
Xamarin is not compatible with my current .NET Core project infrastructure.

**Comment by dbrodie** [comment]
I have a M1 Mac and would be happy to provide some help in porting it over and verifying that it works. This is doubly important for the M1 Mac's as Samsung's official app doesn't seem to work there.

Do you have a branch that you are working on where I could take a look at implementing some of the interfaces?

**Comment by junkaiman** [comment]
Is there any schedule for the Mac OS version?

**Comment by sebastian-greco** [comment]
Is there any way to support you economically in this specific port? I'm guessing I'm not the only one that would be glad to do so.

**Comment by lukasong** [comment]
Is the Mac port not going to happen anymore?

**Comment by sidevesh** [comment]
Also interested in this

**Comment by ThePBone** [comment]
I put my current Bluetooth backend implementation for macOS up on another branch: https://github.com/ThePBone/GalaxyBudsClient/tree/osx-backend-prototype

It is basically finished with a few bugs that still need to be fixed. The UI works on Mac already (last time I checked), so now only the Bluetooth backend for macOS needs to be integrated with the main GalaxyBudsClient project. 

I only have an old 2011 MacBook Pro (on OSX 10.13), so I cannot help with the new ARM-based Macs. 

If someone would like to pick this up, feel free to do so. I don't know yet if and when I'll get around to experimenting with this.

**Comment by katlehotech** [comment]
Is it possible to add bounty for this issue for whoever solves it?

**Comment by BKPepe** [comment]
I agree, this would be really helpful to have at least on Macs, which are not based on ARM.

**Comment by pedroserigatto** [comment]
would there need to be a second port for the app to work on apple silicon? Or Rosetta 2 solves it?

**Comment by ThePBone** [comment]
macOS support is now being tracked in this issue: #449
