### ISSUE TITLE
Microphone Boost

### ISSUE THREAD

**Issue by TheCopperDragon** [ThePBone/GalaxyBudsClient#116]
Is it at all possible to implement a microphone boost feature?
I use my Buds Live a lot with Teams on PC but the microphone volume is really low meaning its difficult for participants to hear me. It seems to be a very common issue judging from google searches.
If I use the buds via my Galaxy phone, then microphone volume is not an issue.

**Comment by ThePBone** [comment]
No, the Buds don't have any boosting capabilities that could be controlled with this app. You could check the Windows audio control panel or use software like Voicemeeter to intercept your microphone input and boost it.
