### ISSUE TITLE
[BUG] not founding connected buds pro

### ISSUE THREAD

**Issue by PubCyBerry** [ThePBone/GalaxyBudsClient#119]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7/8/8.1/10 [Home / Pro] [32bit / 64bit] OS Build number
 - Application version: 

**Additional context**

OS: Window 10 Pro 64bit
OS Build Number: 19042.746
I connected my buds pro to the desktop and installed buds client.
During installation, after selecting laguage, i keep seeing 'no paired device found' message.

![image](https://user-images.githubusercontent.com/44991602/105978300-bbcce500-60d5-11eb-8531-23f931fc6cc9.png)

**Comment by ThePBone** [comment]
Did you try to press on the "Refresh paired devices" button a few times after the earbuds are connected?

**Comment by PubCyBerry** [comment]
> Did you try to press on the "Refresh paired devices" button a few times after the earbuds are connected?

yes of course. 
I tried rebootting desktop and reset earbud etc but exerthing not working.

**Comment by ThePBone** [comment]
That's strange...
Could you try to upload the application log file here?
You can get it like this:
1. Press 'Win+R' and enter `%LOCALAPPDATA%\GalaxyBudsClient\`
2. Upload the `application.log` from the folder that just opened

**Comment by jmace2** [comment]
I'm having this same issue with my buds live: 
![image](https://user-images.githubusercontent.com/43765482/106331953-6e728400-624b-11eb-8507-c83b3914520d.png)

**Comment by jmace2** [comment]
[application.log](https://github.com/ThePBone/GalaxyBudsClient/files/5896518/application.log)
(here is my application log)

**Comment by ThePBone** [comment]
It looks like the new Windows 10 update 20H2 breaks the WinRT Bluetooth APIs. You can try to use [v3.2.0.0](https://github.com/ThePBone/GalaxyBudsClient/releases/3.2.0.0) (which still uses the legacy Win32 Bluetooth APIs)  until I have a fix for this.

**Comment by ThePBone** [comment]
I have reverted to the old Bluetooth backend and added the new one as an optional choice since it doesn't support all Bluetooth adapters.

You can download pre-compiled beta Windows binaries with the new changes here:
https://github.com/ThePBone/GalaxyBudsClient/actions/runs/528620347

If you already managed to register a device, but it doesn't want to connect, you need to remove it first: `Options > Unregister device`.
When you are back on the device selection page, keep the `Use alternative Bluetooth backend` toggle **disabled**!

**Comment by ThePBone** [comment]
Version 4.1 implements a workaround for this issue: https://github.com/ThePBone/GalaxyBudsClient/releases/tag/4.1.0.0

You may need to repeat this procedure:

If you already managed to register a device, but it doesn't want to connect, you need to remove it first: `Options > Unregister device`.
When you are back on the device selection page, keep the `Use alternative Bluetooth backend` toggle disabled!
