### ISSUE TITLE
[BUG] ANC Control doesn't work for GB Live

### ISSUE THREAD

**Issue by brkbrlz16** [ThePBone/GalaxyBudsClient#122]
As the title says, I'm unable to control ANC on my Galaxy Buds Live using the app. The switch doesn't work for turning it off. I hear the "ANC on sound" even when I try to turn it off. That started happening after the update which introduced Buds Pro support I think.

 - OS: Windows 10 Home x64 20H2
 - Application version: 4.0.2.0

**Comment by cozyplanes** [comment]
Yes, it is happening since some time ago. Only way to turn off when no Android device is nearby is to assign touch control to ANC on/off

**Comment by ThePBone** [comment]
I fixed this issue with version 4.1. Executables are available in a few minutes on the release page: https://github.com/ThePBone/GalaxyBudsClient/releases/tag/4.1.0.0
