### ISSUE TITLE
[BUG] GalaxyBudsClient v4.0.2 Not connecting 

### ISSUE THREAD

**Issue by spoofgq** [ThePBone/GalaxyBudsClient#123]
When I updated to the newer version it won't pair with my galaxy buds anymore
Here is the application.log with the errors
[application.log](https://github.com/ThePBone/GalaxyBudsClient/files/5897431/application.log)

**Comment by ThePBone** [comment]
```
2021-01-30 00:22:25.807 -05:00 [ERR] WindowsRT.BluetoothService: Error while getting Bluetooth device from cached id: The parameter is incorrect.
```

It looks like some settings have been saved incorrectly or were corrupted. Could you try to close the app (in the tray bar as well) and delete `config.json`? (in the same folder as `application.log`)

**Comment by spoofgq** [comment]
> ```
> 2021-01-30 00:22:25.807 -05:00 [ERR] WindowsRT.BluetoothService: Error while getting Bluetooth device from cached id: The parameter is incorrect.
> ```
> 
> It looks like some settings have been saved incorrectly or were corrupted. Could you try to close the app (in the tray bar as well) and delete `config.json`? (in the same folder as `application.log`)

I tried that a couple times actually and no bueno. It looks like only v3.3 works for me now, which is odd because before the update i was on v4.0

**Comment by ArthurWolfhound** [comment]
Have you tried reinstalling or updating your Bluetooth drivers? I know it sounds not exactly related, but that's Windows we're talking about 🙃 ... You can also try performing System Integrity Check, though I doubt it would help at all...

1. Open elevated to Admin Windows Powershell. Depending from system to system you may be able to press Win+X and find Windows Powershell (Admin) there. If not - use Windows search, right-click, open as Admin.
2. Run command `DISM.exe /Online /Cleanup-image /Restorehealth`, do mind that you need internet connection to use this command. At this stage operating system will analyze if any files are missing or corrupted and then will download them from Microsoft Servers.
3. Now you will need to run command `sfc /scannow`, this time it is going to apply files to your system.
4. Reboot.

**Comment by spoofgq** [comment]
> 
> 
> Have you tried reinstalling or updating your Bluetooth drivers? I know it sounds not exactly related, but that's Windows we're talking about 🙃 ... You can also try performing System Integrity Check, though I doubt it would help at all...
> 
>     1. Open elevated to Admin Windows Powershell. Depending from system to system you may be able to press Win+X and find Windows Powershell (Admin) there. If not - use Windows search, right-click, open as Admin.
> 
>     2. Run command `DISM.exe /Online /Cleanup-image /Restorehealth`, do mind that you need internet connection to use this command. At this stage operating system will analyze if any files are missing or corrupted and then will download them from Microsoft Servers.
> 
>     3. Now you will need to run command `sfc /scannow`, this time it is going to apply files to your system.
> 
>     4. Reboot.

I have tried running a sys integrity check and reinstalled my bluetooth drivers and even tried using a external usb bluetooth adapter, It seems it might be something with the 4.0.0 versions, all the older versions seem to be working fine. It's really weird

**Comment by ThePBone** [comment]
It looks like the new Windows 10 update 20H2 breaks the WinRT Bluetooth APIs. You can try to use [v3.2.0.0](https://github.com/ThePBone/GalaxyBudsClient/releases/3.2.0.0) (which still uses the legacy Win32 Bluetooth APIs)  until I have a fix for this.

**Comment by spoofgq** [comment]
> Windows 10 update 20H2 breaks the WinRT Bluetooth APIs

Yeah that makes more sense now, I did update the 20H2 recently

**Comment by ThePBone** [comment]
I have reverted to the old Bluetooth backend and added the new one as an optional choice since it doesn't support all Bluetooth adapters.

You can download pre-compiled beta Windows binaries with the new changes here:
https://github.com/ThePBone/GalaxyBudsClient/actions/runs/528620347

If you have already registered a device, but it doesn't want to connect, you need to remove it first: `Options > Unregister device`
When you are back on the device selection page, keep the `Use alternative Bluetooth backend` toggle **disabled**!

**Comment by ThePBone** [comment]
Version 4.1 implements a workaround for this issue: https://github.com/ThePBone/GalaxyBudsClient/releases/tag/4.1.0.0

You may need to repeat this procedure:

If you already managed to register a device, but it doesn't want to connect, you need to remove it first: `Options > Unregister device`.
When you are back on the device selection page, keep the `Use alternative Bluetooth backend` toggle disabled!
