### ISSUE TITLE
[REQ] Command Line Support

### ISSUE THREAD

**Issue by Bricktheworld** [ThePBone/GalaxyBudsClient#124]
Could we possibly be able to interface with the client through terminal queries? I'd love to help on this if you need it, although this doesn't actually seem terribly difficult to implement. The only thing I really need to query is the battery so that I can put it in polybar as a module. I don't know how hard this is, but if we could just run the application with command line arguments like "./GalaxyBudsClient.bin --battery" and it would just spit out the current battery of both buds. That would be a great feature so that we can make the app scriptable for Linux. 

If you need help with this please let me know and I'll look into it!

Thank you!

**Comment by ThePBone** [comment]
I'll add it to my to-do list. 
For now, you can also use this script to read battery values from Galaxy Buds(+) devices: https://github.com/ThePBone/GalaxyBuds-BatteryLevel

Unfortunately, only one application can access the Bluetooth socket at a time. While the script is active, you won't be able to connect using this app.

**Comment by Bricktheworld** [comment]
Oh wow this is actually perfect for me! I don't actually need anything else other than this so you can close this issue if you feel like it :) Although I imagine there might be a few other users who would want to use this script at the same time as the app

**Comment by Bricktheworld** [comment]
In case anyone wants a way to add their galaxy buds to polybar, here is the module I quickly made with the galaxy buds level package

`[module/galaxbuds]
type = custom/script
exec = galaxybuds-batterylevel <Mac Address>
exec-if = bluetoothctl info | grep <Mac Address>
tail = true
label =  %output%
interval = 60
`

**Comment by ThePBone** [comment]
I am going to close this now since I probably won't add command line support. Instead, I can provide standalone Python scripts (like the one above or this one: [ThePBone/BudsPro-Headtracking](https://github.com/ThePBone/BudsPro-Headtracking)) if someone has a specific request to include in his own project.
