### ISSUE TITLE
[BUG] "The Provided device ID is not a valid BluetoothDevice object"

### ISSUE THREAD

**Issue by snappy-tech** [ThePBone/GalaxyBudsClient#125]
I have attempted conntecting to my Galaxy Buds+ on two different versions of the application (4.0.2, 4.0) and am unable to connect them.

The buds are definitely connected to Windows, as I can use them normally, and have already attempted un-pairing and re-pairing to no avail. Below I have attached a screenshot of the error, and the application.log.

64-bit Windows version 20H2 (OS Build 19042.782)

![image](https://user-images.githubusercontent.com/56049290/106371158-13c74e00-6359-11eb-94a7-bd5260b5226e.png)
[application.log](https://github.com/ThePBone/GalaxyBudsClient/files/5898989/application.log)

**Comment by ArthurWolfhound** [comment]
Judging by `application.log`, something similar was referenced in issue #123. As I see, that you know where to get `application.log`, did you try closing app completely (including via tray icon) and deleting `config.json` (in the same folder)?

I also did provide instructions for System Integrity check (though I doubt it would help, it would not hurt) - [here](https://github.com/ThePBone/GalaxyBudsClient/issues/123#issuecomment-770314173)

**Comment by snappy-tech** [comment]
I attempted deleting the config file with both versions and there was no improvement. System integrity is fine, and Bluetooth drivers are all up to date. 

I have just installed v3.3 and everything is working as expected. As with #123, I suspect that v4 is where the bug begins.

**Comment by ThePBone** [comment]
It looks like the new Windows 10 update 20H2 breaks the WinRT Bluetooth APIs. You can try to use [v3.2.0.0](https://github.com/ThePBone/GalaxyBudsClient/releases/3.2.0.0) (which still uses the legacy Win32 Bluetooth APIs)  until I have a fix for this.

**Comment by ThePBone** [comment]
I have reverted to the old Bluetooth backend and added the new one as an optional choice since it doesn't support all Bluetooth adapters.

You can download pre-compiled beta Windows binaries with the new changes here:
https://github.com/ThePBone/GalaxyBudsClient/actions/runs/528620347

If you have already registered a device, but it doesn't want to connect, you need to remove it first: `Options > Unregister device`
When you are back on the device selection page, keep the `Use alternative Bluetooth backend` toggle **disabled**!

**Comment by snappy-tech** [comment]
Thank you for your rapid response! I have installed the beta and am happy to confirm that it is working as expected.

**Comment by ThePBone** [comment]
Version 4.1 implements a workaround for this issue: https://github.com/ThePBone/GalaxyBudsClient/releases/tag/4.1.0.0

You may need to repeat this procedure:

If you already managed to register a device, but it doesn't want to connect, you need to remove it first: `Options > Unregister device`.
When you are back on the device selection page, keep the `Use alternative Bluetooth backend` toggle disabled!

**Comment by snappy-tech** [comment]
Just a quick heads-up that the Windows 10 21H1 update does **not** seem to have fixed the WinRT Bluetooth APIs.
