### ISSUE TITLE
[REQ] MIC support

### ISSUE THREAD

**Issue by CLocke26** [ThePBone/GalaxyBudsClient#126]
**Describe the solution you'd like**
Pairing my buds live should give the audio device the ability to act as a mic

**Describe alternatives you've considered**
It'd be nice to pair my buds and not have to worry about a separate device for audio on calls 

**Additional context**
I could be missing the feature, my device was paired as a headphone by default. I'm not sure I missed it or maybe the feature isn't even possible

![image](https://user-images.githubusercontent.com/22862088/106372068-8290b100-6331-11eb-8242-bf9a91365d0e.png)
![image](https://user-images.githubusercontent.com/22862088/106372072-8cb2af80-6331-11eb-9ce5-0d3064443e80.png)
![image](https://user-images.githubusercontent.com/22862088/106372075-920ffa00-6331-11eb-8cd0-dabd18aa369c.png)

Awesome work, my buds have been collecting dust working from home. This project revitalized them

**Comment by ArthurWolfhound** [comment]
Could you please elaborate on what you meant?

I have Buds+ and they are installed in the system as two devices, Headset and Headphones - application like Zoom or Discord should automatically understand what to connect.

**Comment by CLocke26** [comment]
@ArthurWolfhound is this different for you?

It does show up as an input option, however I cannot get audio to come out of it when I test

![image](https://user-images.githubusercontent.com/22862088/106373099-e91acc80-633b-11eb-84f6-afdc80dc78f6.png)

**Comment by CLocke26** [comment]
@ArthurWolfhound I must be mistaken, It is now working. I'm not sure what changed. Don't mind me.

Thanks for the great work!

**Comment by CLocke26** [comment]
Perhaps you could answer me this I guess

In discord when I set the audio to input from the buds live, my output out of discord does not work and I hear no sound?

![image](https://user-images.githubusercontent.com/22862088/106373213-f97f7700-633c-11eb-84d0-ee089813b706.png)

**Comment by CLocke26** [comment]
Ok this is going to get even more confusing/weird

In discord, if I use my headset (buds live) as input, it will break my audio connection whenever they're in use as a mic IE testing window or in a call. If I leave the call/testing window I hear output from external sources (twitch) if I join a call/testing window (mic in use) it all drops.

I have no idea

**Comment by ArthurWolfhound** [comment]
Discord is a little more aggressive then other programs and takes over to run in background (or while gaming) correctly. It is the same for me.
