### ISSUE TITLE
[BUG] 100% CPU utilization on Linux

### ISSUE THREAD

**Issue by EtienneDesticourt** [ThePBone/GalaxyBudsClient#127]
Hi!

**Describe the bug**

When open the application consumes 100% of a CPU core on linux.

**To Reproduce**
1. Open the application.
2. Connect to earbuds.
3. Listen to your fans go wild
4. run `top`
5. See GalaxyBudsClient at 100% CPU usage

**Expected behavior**
Reasonable CPU util.

**Desktop (please complete the following information):**
 - OS: Ubuntu 64bits 20.04
 - Application version: 4.0.2

Cheers

**Comment by ThePBone** [comment]
Sorry for the delay on this. This issue is now fixed, the CPU usage is now significantly reduced.
You can grab the latest precompiled binary for your architecture here https://github.com/ThePBone/GalaxyBudsClient/actions/runs/901139843
