### ISSUE TITLE
First time using 4.0.1 and 4.0.2 not able to connect Buds Live

### ISSUE THREAD

**Issue by ElArcangel** [ThePBone/GalaxyBudsClient#131]
I'm a first time user so can't say if it was working on previous versions or not but installed 4.0.1 and a friend of mine too, both have Buds Live and both received same error message to connect "ConnectFailed: An invalid argument was supplied". A day after that, 4.0.2. version was out so I tested to check if that fixed the issue with no luck.
Tested also version 3.2 as a workaround and connected successfully on that one but on any menu I go, when i click on back button, same error message to connect and need to unpair so apparently something not working either on old version.
I'm on windows 10 1909 so not related to 20H2 version but maybe it's a security patch that changes something and introduces same issue present on 20H2 (just a guess)
No logs on event viewer to share and %localappdata%\ThePBone_(Tim_Schneeberge deleted already.

any clue or advice will be welcome.

**Comment by ThePBone** [comment]
For now, you can try to use [version 3.3](https://github.com/ThePBone/GalaxyBudsClient/releases/tag/3.3.0.0)

I'll try to update and revert the default Bluetooth backend to the legacy one soon.

**Comment by ThePBone** [comment]
I have reverted to the old Bluetooth backend and added the new one as an optional choice since it doesn't support all Bluetooth adapters.

You can download pre-compiled beta Windows binaries with the new changes here:
https://github.com/ThePBone/GalaxyBudsClient/actions/runs/528620347

If you have already registered a device, but it doesn't want to connect, you need to remove it first: `Options > Unregister device`
When you are back on the device selection page, keep the `Use alternative Bluetooth backend` toggle **disabled**!

**Comment by ElArcangel** [comment]
Thanks for such quick response. Tried the new version and re registered with the option you mentioned disabled. Now it does not give any error but seems not to connect since buds image has a spinning wheel on the top right that never ends, also any command I trigger seems to not have effect and when I go to system information, all items are in a "waiting for response..." status

Not sure if I can grab any log from the app itself that can help you debug this error.
Still no events on event viewer

**Comment by ElArcangel** [comment]
Hi Tim, quick question probably related to this issue. Does this app need to have "find nearby devices" feature enabled on windows in order to work? I have it blocked on my computer due to security policies but apparently it will get unblocked in 2 weeks approx since many complained that several Bluetooth headsets stopped working after that blocking.
Will test again after the unblocking and let you know if anything changes of course.

**Comment by ElArcangel** [comment]
Hi Team, good news. Nearby devices windows feature is working again and since then, app also started working so apparently, app wont work without "allow nearby devices" active on windows.

**Comment by ThePBone** [comment]
That's good to know, I'll see if I can detect whether this setting is disabled and display a warning message accordingly.
