### ISSUE TITLE
Delay on connection when pressing connect button on the tray icon

### ISSUE THREAD

**Issue by giovanniro98** [ThePBone/GalaxyBudsClient#132]
Windows 10 64bit
When i press the connect button the connection to the pc happens with a delay of 5-10s:
I press connect button and the pc show that the buds are connected (on notification menu tiles), then i try to reproduce something and the audio come from the pc's speakers. After 5-10s I hear the connection sound on the buds and the pop up comes up (sometimes) and from that moment everything works fine.
Is this behaivour fixable or improvable?

**Comment by ThePBone** [comment]
Yes, this is normal. The Windows A2DP driver that handles the Bluetooth audio stream takes much more take to initialize and is a bit unreliable sometimes.
