### ISSUE TITLE
Received Corrupted data Reconnecting...  (Overflow)

### ISSUE THREAD

**Issue by rhinounicorn** [ThePBone/GalaxyBudsClient#135]
Windows 10 64bit
I have the OG Buds and when I updated to the latest version (v4.0.2) I get this error message and it just keeps trying to reconnect and nothing works. I've tried using the old versions all the way to version 3.2 but nothing seems to work. Is this a problem in my buds?
https://ibb.co/fXwjrHS
https://ibb.co/kX2vNqT
https://ibb.co/NSWfxCh

**Comment by cozyplanes** [comment]
Forget the connected Buds in windows bluetooth settings
Win+ I (the alphabet eye) > devices > bluetooth > galaxy buds > remove device

**Comment by rhinounicorn** [comment]
I think I've already tried that but I'll give it another shot later

**Comment by ThePBone** [comment]
I released a new version that allows you to fall back to another Bluetooth backend: https://github.com/ThePBone/GalaxyBudsClient/releases/tag/4.1.0.0

You can enable it like this:
1. Unregister your earbuds in the app if not already done, like this: `Options > Unregister device`
2. Proceed to the device selection page
3. **Disable the switch with the label 'Use alternative Bluetooth backend'**
4. Select your earbuds from the list and continue

I don't know if it solves your issue, but it's worth a try.

**Comment by rhinounicorn** [comment]
So far this has worked. I'll update if anything comes up later. Thanks for the help, and I love the app
