### ISSUE TITLE
[BUG] Case battery percentage is always 0 or 101%

### ISSUE THREAD

**Issue by johnmagbag1995** [ThePBone/GalaxyBudsClient#139]
Buds Pro case battery percentage is always shows 0 or 101% using v4.0.2

![image](https://user-images.githubusercontent.com/61783659/107116706-0d345b80-68b0-11eb-8dda-267cd2369db4.png)

**Comment by ctrousdale** [comment]
I can replicate the issue when the case is closed, however opening the case will then display the correct battery level. This behavior is similar to the Galaxy Wearables app on mobile (when the case is closed its battery level isn't reported).

**Comment by ThePBone** [comment]
The Buds Pro always report a 101% battery percentage if the case is unavailable; I thought I already accounted for this, but it looks like values over 100% can still slip through. I'll have a look at this soon.

**Comment by ThePBone** [comment]
I fixed this issue with version 4.1. Executables are available in a few minutes on the release page: https://github.com/ThePBone/GalaxyBudsClient/releases/tag/4.1.0.0
