### ISSUE TITLE
Pull the latest version down please

### ISSUE THREAD

**Issue by SnakeSK** [ThePBone/GalaxyBudsClient#149]
This is a non working version for 20H2 (majority) of users, please pull the latest version or force a downgrade for the app.

**Comment by ThePBone** [comment]
Version 4.1 implements a workaround for this issue: https://github.com/ThePBone/GalaxyBudsClient/releases/tag/4.1.0.0

You may need to repeat this procedure:

If you already managed to register a device, but it doesn't want to connect, you need to remove it first: `Options > Unregister device`.
When you are back on the device selection page, keep the `Use alternative Bluetooth backend` toggle disabled!
