### ISSUE TITLE
[REQ]

### ISSUE THREAD

**Issue by jaidevpal** [ThePBone/GalaxyBudsClient#151]
**Is your feature request related to a problem? Please describe.**
There was already an option called **"Gaming Mode"**, which was a great option to toggle between modes. It is missing after an update.

**Describe the solution you'd like**
Please get that **Gaming Mode** option back.

**Comment by ThePBone** [comment]
The Gaming Mode option was not functional since Gaming Mode only supports Android devices running OneUI 3 or later.
There is no point in including an option that has no effect on computers or other non-android devices.
