### ISSUE TITLE
[REQ] Update the icon

### ISSUE THREAD

**Issue by Joedmin580** [ThePBone/GalaxyBudsClient#153]
I think the icon could be the same as on the phones, so with the white text in the orange background.
![Galaxy Wearable icon](https://play-lh.googleusercontent.com/z5UFW9brV68Mo0YuHpcl6z7GEXNHje6guM8Z6jJoOWB_GjdYra8pn2Hs-qyXCdvjVA)

**Comment by ThePBone** [comment]
I changed the Wearable icon colors to clearly differentiate it from the official Windows Galaxy Buds firmware updater by Samsung. Their program already uses the orange icon and could confuse some people if I'd use the same colors for my app:

![image](https://user-images.githubusercontent.com/38386967/108114594-48494280-7099-11eb-8d07-572220086cee.png)
