### ISSUE TITLE
Unable Run On Linux

### ISSUE THREAD

**Issue by ManmohanGill** [ThePBone/GalaxyBudsClient#159]
I'm attempting to run this on Linux, but it seems like it cant be run at all 

![Screenshot from 2021-02-21 11-30-01](https://user-images.githubusercontent.com/18358271/108614755-5bad3280-7438-11eb-9df2-a9b26dafcf49.png)

Aded Screenshot

**Comment by ThePBone** [comment]
What processor architecture is your computer running on?
Also, could you run 
```
file Buds.bin
```
and post the output of that command here?

**Comment by whale124** [comment]
If you run "GalaxyBudsClient_Linux_64bit-musl_Portable.bin" from AMD64 architecture, the corresponding error appears.

**Comment by ThePBone** [comment]
The 64bit-musl executable is not for regular amd64 distros. Some amd64 Linux distributions like Alpine Linux use a special and more lightweight libc variant called "musl". This executable is only for these, it won't run on normal amd64 distros.

Please use 'GalaxyBudsClient_Linux_64bit_Portable.bin' instead.

**Comment by mykeysr** [comment]
Same error, can't able to run on Ubuntu 22.04.1 LTS.

```
file buds.bin 
buds.bin: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=0d78e22dc15d366dce0f9844639a3b96ac2e139d, for GNU/Linux 2.6.32, stripped, too many notes (256)

```

**Comment by achede22** [comment]
```
file GalaxyBudsClient_Linux_arm64_Portable.bin 

GalaxyBudsClient_Linux_arm64_Portable.bin: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=de45bf16818bcdd97d68304188f55ac9677cd74d, stripped
```

```
bash GalaxyBudsClient_Linux_arm64_Portable.bin 
GalaxyBudsClient_Linux_arm64_Portable.bin: GalaxyBudsClient_Linux_arm64_Portable.bin: cannot execute binary file
```

```
uname -a #ubuntu 22.04.1 LTS

Linux achede-IdeaPad-3-15ALC6 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ThePBone** [comment]
@achede22 That's the wrong CPU architecture. In your case, you need to download the regular 64bit version (not arm64).
