### ISSUE TITLE
[BUG] Low Latency Game Mode Missing for Buds+ ?

### ISSUE THREAD

**Issue by kimpurcell** [ThePBone/GalaxyBudsClient#160]
For some reason I can't find the low latency Game Mode option. I have a pair of Buds+.

**Comment by stylemessiah** [comment]
That because that mode is only available on Samsung phones as it relies on a codec that is only on Samsung devices

**Comment by ThePBone** [comment]
The Gaming Mode option is not functional on Windows since Gaming Mode only supports Android devices running OneUI 3 or later.
There is no point in including an option that has no effect on computers or other non-android devices.
