### ISSUE TITLE
[BUG] Garbled connection at start of audio feed. Gets worse with progressive restarting/refreshing of video in Chrome.

### ISSUE THREAD

**Issue by derenma** [ThePBone/GalaxyBudsClient#161]
**Describe the bug**
Bluetooth connection is "garbled" during the first few seconds (up to a minute) when YouTube videos are reloaded. 

**To Reproduce**
1. Open YouTube, start a video. (There is a little bit of garble at first.)
2. Click refresh on your browser. (Audio will be garbled more)
3. Refresh video. (Issue will get worse.)
4. Kill GBC, kill browser.
5. Reopen GBC. Reopen browser.
5. Repeat from step 1 and the issue gets worse with every new video or refresh.

**To Fix**
1. Kill GBC

**Expected behavior**
Non-sporadic compression issues?

**Screenshots**
Totally an audio issue.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64bit / 19042.804, 20H2
 - Application version:  4.1

**Additional context**
During the start of audio, it actually sounds like BT interference. I suspect it's some kind of buffering issue, but I don't know squat about the BT stack, so who knows?

**Comment by ThePBone** [comment]
The issue might have been fixed during recent updates (-> major release v4.2). Reopen if this persists.
