### ISSUE TITLE
Multipoint?

### ISSUE THREAD

**Issue by danergo** [ThePBone/GalaxyBudsClient#188]
Hi, 

this question by its nature would be a but outstanding in here, sorry for that:
I'm chasing for a solution for this situation:
When I pair the Buds with 2 different devices, the Buds always try connecting to the lastly connected device.
No matter if that one is unavailable, the Buds is not that smart to jump onto the next one.

Do you maybe have any idea on how can I ask Buds to not give up if last connected device is unavailable?

**Comment by ThePBone** [comment]
Unfortunately, I don't think it is possible to change the connection behavior of the buds. They would need a firmware update from Samsung to achieve something like this.
