### ISSUE TITLE
[UI Issue] Custom actions not visible

### ISSUE THREAD

**Issue by ArthurWolfhound** [ThePBone/GalaxyBudsClient#19]
![image](https://user-images.githubusercontent.com/16789106/89710081-b8f40180-d988-11ea-8ff7-dcfcca013223.png)
![image](https://user-images.githubusercontent.com/16789106/89710090-ca3d0e00-d988-11ea-8064-360bce92d663.png)

Hi! Looks like UI when choosing custom actions is broken in both light and dark themes.

By the way, is it possible to make application respect system-wide light and dark themes? I use custom powershell script from PSGallery to switch my Windows themes, look [here](https://github.com/markwragg/powershell-lumos) if interested. 

I also know that system-wide theme is set by reg key 

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize] "AppsUseLightTheme"=dword:00000001 for light (dword:00000000 for dark), maybe it helps.

Would be neat. And is there a way to open discussions instead of issues?

Kind regards,
Friendly contributor.

P.S. Only began learning software development (student) - but at least working on russian and ukrainian xamls for translation, also will do readme.

**Comment by ThePBone** [comment]
I'll have a look at it later today, that's probably a localization issue.

> By the way, is it possible to make application respect system-wide light and dark themes?

Sure, I can add an extra setting for this.

> working on russian and ukrainian xamls for translation

Thanks! By the way, if you rename the modified XAML file to `custom_language.xaml` and place it into the same folder the executable is in, the app will enter a translation mode and open a small debug dialog for translators which can hot-reload the XAML while the app is still running. You can also switch to any page using the dialog, so you can properly review your changes. (Requires version 2.3 or later)

**Comment by ArthurWolfhound** [comment]
It. Just doesn't work...

Did I place it correctly?
![image](https://user-images.githubusercontent.com/16789106/89711321-438d2e80-d992-11ea-9a98-e3ad6843cee2.png)

I run it. It dies. Tried to run it with admin. It dies. 
Just sits in task manager for like 15 seconds and dies...

Is it possible that because my Windows is set to English it breaks because of cyrillic text?
Oh no wait. I have this thing set...
![image](https://user-images.githubusercontent.com/16789106/89711343-6b7c9200-d992-11ea-9cd8-124766113921.png)

Weird...
Can I get any logs from anywhere?

**Comment by ArthurWolfhound** [comment]
And now even after removing `custom_language.xaml` from folder it is...broken? Re-installing it and trying again.

Re-installed it. It now just doesn't work. Starts. And then instantly dies. How did I manage to break it?

**Comment by ThePBone** [comment]
Wait, what? Maybe the configuration storage was corrupted, try deleting all files in `C:\Users\<username>\AppData\Local\ThePBone(...)`

**Comment by ArthurWolfhound** [comment]
Just did that. Windows was shouting at me about insufficient permissions (What???)
Force set myself as folder owner (It was tied to ADMINISTRATORS Group, but I am the admin, what?)

- Killed whole folder.
- Deleted the app.
- Cleaned temp and registry with CCleaner.
- Installed it again.
- Nope. Tottaly dead.

**Comment by ThePBone** [comment]
> Windows was shouting at me about insufficient permissions
Probably because you ran it in admin mode, it set to permissions in C:\Users\<username>\AppData\Local\ThePBone to the administrator account as well.

**Comment by ThePBone** [comment]
The conf storage is not created instantly, only after registering a new device or changing other settings within the app.

**Comment by ArthurWolfhound** [comment]
But it just doesn't start now...
No GUI. Dies within seconds...

**Comment by ThePBone** [comment]
For some reason, it crashes silently and .NET does not display a detailed error message. 

There are a few ways to debug that: 

* Look into the event viewer (go to Windows Logs -> Applications and search for '.NET runtime')

* Get a crash dump. Normally Windows should store crashdumps here: `%localappdata%\CrashDumps`

**Comment by ArthurWolfhound** [comment]
- Restart my dumb laptop
- App is back alive
- Get `custom_language.xaml` back into folder
- App is dead again
- `<sys:String x:Key="ResourceDictionaryName">Loc-en</sys:String>` maybe ru? - no, maybe custom? - no
- Get rid of `custom_language.xaml`
- App is alive again.

Checking dumps immediately.

**Comment by ThePBone** [comment]
Strange. The other translator had no issue with it for some reason.

Try to remove the XAML from C:\Program Files\... and create a copy of the app directory in another (normal) folder with normal privileges (like another volume or your user directory) and run it with the XAML from there.

Maybe it can't access the XAML file in C:\Program Files and therefore crashes.

**Comment by ArthurWolfhound** [comment]
Got logs in the event viewer. Do I save those as evtx (Event files)?

**Comment by ThePBone** [comment]
Maybe? I've never used it to save logs. Copy and pasting should be okay too if possible.

**Comment by ArthurWolfhound** [comment]
[GalaxyBudsManagerCrash.zip](https://github.com/ThePBone/GalaxyBudsClient/files/5045375/GalaxyBudsManagerCrash.zip)

Checked it. Should just open with double click.

**Comment by ThePBone** [comment]
The `custom_language.xaml` seems to be malformed, could you share it here?

This is the exception stack trace:

	Exception Info: System.Windows.Markup.XamlParseException
	   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
	   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, Boolean, System.Uri)
	   at System.Windows.Markup.XamlReader.Load(System.Xaml.XamlReader, System.Windows.Markup.ParserContext)
	   at System.Windows.Markup.XamlReader.Load(System.Xml.XmlReader, System.Windows.Markup.ParserContext, System.Windows.Markup.XamlParseMode, Boolean, System.Collections.Generic.List`1<System.Type>)
	   at System.Windows.Markup.XamlReader.Load(System.IO.Stream, System.Windows.Markup.ParserContext, Boolean)
	   at System.Windows.Markup.XamlReader.Load(System.IO.Stream, System.Windows.Markup.ParserContext)
	   at MS.Internal.AppModel.AppModelKnownContentFactory.XamlConverter(System.IO.Stream, System.Uri, Boolean, Boolean, Boolean, Boolean, System.Windows.Markup.XamlReader ByRef)
	   at MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStream(System.IO.Stream, MS.Internal.ContentType, System.Uri, Boolean, Boolean, Boolean, Boolean, System.Windows.Markup.XamlReader ByRef)
	   at System.Windows.ResourceDictionary.set_Source(System.Uri)
	   at Galaxy_Buds_Client.util.DynamicLocalization.Loc.SetLanguageResourceDictionary(System.String)
	   at Galaxy_Buds_Client.util.DynamicLocalization.Loc.Load()
	   at Galaxy_Buds_Client.App.App_Startup(System.Object, System.Windows.StartupEventArgs)

**Comment by ArthurWolfhound** [comment]
GitHub actually does not allow xamls here 🙃 

Could it be because of the fact that I added some personal commentary?
[ruxaml.zip](https://github.com/ThePBone/GalaxyBudsClient/files/5045389/ruxaml.zip)

**Comment by ThePBone** [comment]
Yes, it was caused by the `<TODO>` tags. You can include translator comments, but they must be wrapped in comment blocks like this: 
```
<!--TODO: xxx-->
```

**Comment by ArthurWolfhound** [comment]
Jeeze! All that for those little things that I've just forgot to remove and change to comments! Sorry for wasted time!
While I am here. What is (en.xaml:45)`<sys:String x:Key="touchoption_quickambientsound">Quick Ambient Sound</sys:String>` ? I've never encountered that option!

**Comment by ThePBone** [comment]
No worries :D

Quick ambient is only available for the older Buds. It could be used to enable ambient sound while one touchpad was held down and to disable it when you let go.

**Comment by ArthurWolfhound** [comment]
I've did it all!
But not ready to make pull request because my Ukrainian xaml makes it crash even harder. I believe it has to do with fact that some words use apostrophes as their parts, but you've used it in popup header and it worked. Maybe it is just too much apostrophes. 

[CrashUKR.zip](https://github.com/ThePBone/GalaxyBudsClient/files/5046303/CrashUKR.zip)

If you have time, please look at what an dear mother Earth I broke this time so I can fix my Ukrainian translation, test it, and make pull request.

Thanks!

**Comment by ThePBone** [comment]
This time I have no clue what's going on, the stack trace refers to another thread which makes sure that only one instance of the app is active at a time. (Absolutely unrelated to localization :sweat_smile:)
I'll try to load the XAML tomorrow and debug it further when I have more time and when I am on my Windows system.

Stack trace:
```
Exception Info: System.InvalidOperationException
   at System.Windows.Window.VerifyCanShow()
   at System.Windows.Window.Show()
   at Galaxy_Buds_Client.App.<SingleInstanceWatcher>b__5_1()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at Galaxy_Buds_Client.App.Main()

```

**Comment by ArthurWolfhound** [comment]
Decided to run it right now. Yep. Works as nothing happened. Ran it several times. Everything just peachy. Thanks .Net Framework for being incredibly petty.

That's it. You now have a pull request.

**Comment by ArthurWolfhound** [comment]
Just understood that if you already have preset custom action, like open notepad.exe for example.
It does not return what is already set.

![image](https://user-images.githubusercontent.com/16789106/89736688-dbaf1480-da73-11ea-99be-e2fc80af16c3.png)

But I have set notepad to open. And it works. UI Issue, again...

**Comment by ThePBone** [comment]
Whoops, I can reproduce that. I think it broke when I made the strings of those selectable actions localizable.

**Comment by ArthurWolfhound** [comment]
@githubcatw - Connection dialog base _**(current)**_ _or_ 
@githubcatw - Notification popup development ?

Asking because I've completely misunderstood it in README, and just went with translation, but now I've checked changelogs and I see there 

> Connection popup based on #14 by @githubcatw

Should I make a change?

**Comment by ThePBone** [comment]
No, it's alright either way

**Comment by ThePBone** [comment]
Commit eaf7a8acacbb63f4de846f4e61804e416cfc82d3 fixes both UI issues you described

**Comment by ArthurWolfhound** [comment]
Brilliant! Looking forward to the next release!

**Comment by ThePBone** [comment]
Alright, here is a test build which contains all changes until commit f2222abf0a4165272a6fe47a0d11a04dfbd0f5c9 .

### Brief changelog:

* Added Russian and Ukrainian translations (2b6d175bf0f182bc275195c4990e15a8bb63f2ea)
* Updated Japanese and Korean translations (various commits)
* Fix empty touchpad action fields (eaf7a8acacbb63f4de846f4e61804e416cfc82d3)
* Custom connection popup title (6c3c1bae686f3878c39c319b049f537e0df784cb)
* Add option to inherit dark mode system setting (6c3c1bae686f3878c39c319b049f537e0df784cb)
* Properly validate device selection (check if device name contains 'Galaxy Buds') (f2222abf0a4165272a6fe47a0d11a04dfbd0f5c9)

[GalaxyBudsClient_2.3.1_build1.zip](https://github.com/ThePBone/GalaxyBudsClient/files/5048264/GalaxyBudsClient_2.3.1_build1.zip)

I've decided to still include the option to explicitly enable the dark mode (rather than relying solely on the system setting) since Windows 7 (and maybe 8?) don't have an system-based dark mode. Also, some people might prefer to override the dark-mode setting of Windows 10.

It'd be great if you could test this build and check if those bugs still occur on your machine. 

There are also five new strings, I've already copied the English version into all XAML files so if you don't have any change requests, it'd be great if you could translate them as well. (at line ~27-29 and ~241)

**Comment by ArthurWolfhound** [comment]
### To begin with
I honestly spent 20 minutes figuring out how do I sync my fork repo with yours. GitHub where is one-click sync button?

### Charging case
If charging case is dead (0%)- app shows Idle for each Bud (or for me something like "Not wearing") - what actually confused me. Is it possible to set it to display "Case: 0%", so there would be an intuitive link and you won't need to introduce other strings for translation.

### Custom Actions

- I recall if it wasn't set it would show up something like "Not set". Not anymore
![image](https://user-images.githubusercontent.com/16789106/89742256-e6cc6980-daa0-11ea-83f8-db67f5403740.png)

- I am a quick and impulsive person who does everything too fast. I make that double-click - and have no idea what I've clicked for an executable. Same applies to hotkeys. **_But that's me deliberately searching for faults so you can ignore that._**
![image](https://user-images.githubusercontent.com/16789106/89742271-111e2700-daa1-11ea-9200-625d4bcf83cd.png)
  - And then I get back to the main Touchpad menu and see my decision. Seems unintuitive, and even more. If it is path to notepad.exe - it fits. If it is something different, it doesn't. And that's I am not even talking about translated versions.
![image](https://user-images.githubusercontent.com/16789106/89742381-0e700180-daa2-11ea-8ef9-0c7c2ff6016f.png)

So yeah, to sum up - remove helper in the main Touchpad settings, move it as separate message into detailed screen. And what's wonderful? Key combinations or paths do not require translation - and their appearance there will be understandable by the chosen action. However you do need to clear those completely if action was switched from custom once, or make a save function, this one is up to your decision only.

- I've tried setting a custom hotkey, and then changed it back to Voice Assistant. Then I open Custom Action... again and see this:
![image](https://user-images.githubusercontent.com/16789106/89742324-8984e800-daa1-11ea-902a-31579ec99a2d.png)
  - Happily clicking on the Apply... and it stays on the Voice Assistant. So, yeah, am I correct by naming that an uncleared variable?

- Honestly, I've lost focus for 2 seconds, and forgot to which Bud I was assigning my Custom Action. If I am correct, you're using the same page, but somewhere in the background you have control variable that sets if it is left or right. So, you probably can make a text reliable on that.

Just for the sake of my own sanity. I am really sorry. You've spent a lot of time on that software, and here I am just finding those little pieces everywhere where I can.

But I've already finished translation of those strings 😃

**Comment by ThePBone** [comment]
> Is it possible to set it to display "Case: 0%", so there would be an intuitive link and you won't need to introduce other strings for translation.

Well, I never managed to fully discharge the case (at home) because I've plugged it in almost permanently. Additionally to displaying "Case: 0%", I can turn the 'idle' textboxes invisible when the case dies.

>I recall if it wasn't set it would show up something like "Not set". Not anymore

I'm pretty sure this happened because the property containing this value was not (yet) set in the configuration storage (and I killed the check apparently :sweat_smile:)

>I am a quick and impulsive person who does everything too fast. I make that double-click - and have no idea what I've clicked for an executable. Same applies to hotkeys. 

Adding those details is no big deal, I was just too lazy to display them on the custom action screen as well.

> And then I get back to the main Touchpad menu and see my decision. Seems unintuitive, and even more. If it is path to notepad.exe - it fits. If it is something different, it doesn't. And that's I am not even talking about translated versions.

Unfortunately, I can't introduce a multiline label here as it would not really match the design with other dropdowns/detail elements.
Instead, I'll just strip the whole file-path and the 'launch executable' string and display the name of the exe on its own.

>Happily clicking on the Apply... and it stays on the Voice Assistant. So, yeah, am I correct by naming that an uncleared variable?

Yes, in this case, it refers to a property in the persistent config storage as well, which is not reset after choosing a non-custom action.

>If I am correct, you're using the same page, but somewhere in the background you have control variable that sets if it is left or right. So, you probably can make a text reliable on that.

Yep, there's one although solely to determine whether the strings for Volume up or down should be loaded; also easily implementable.

Thanks for your input! I'll get to work later (or tomorrow) and patch those things

**Comment by ThePBone** [comment]
I've fixed all issues you described and published another update (v2.3.1):
<https://github.com/ThePBone/GalaxyBudsClient/releases/tag/2.3.1>

**Comment by ArthurWolfhound** [comment]
Yay! I've already got it actually, just haven't noticed your comment here. (Blame not me. Blame Github's moronic app for Android which has no background syncs).

It was fun to help! Cheers!

**Comment by ThePBone** [comment]
Sure! And thanks a lot for your help :D
