### ISSUE TITLE
[REQ]

### ISSUE THREAD

**Issue by Chikafreak** [ThePBone/GalaxyBudsClient#190]
**Is your feature request related to a problem? Please describe.**
Ambient sounds feature does not work when using Buds+ as voice and audio in Microsoft Teams.

**Describe the solution you'd like**
I would like it if the Ambient Sounds feature worked while on Teams calls.

Thank you so much for this Freeware! You guys are seriously the best, much kudos!

**Comment by ThePBone** [comment]
Unfortunately, I can't do anything about this because this behavior is hard-coded into the firmware of the buds. 
Either the microphone is used for ambient sound or voice transmission, but it cannot do both at once
(maybe this is due to technical limitations on the buds as well).

**Comment by Chikafreak** [comment]
Got it! Well thank you very much. I did notice that the buds cannot unmute
during a Teams call either. I believe this is because the buds treat a
Team's call more as music than a voice phone call (which can be muted).
Thanks so much for your help!
