### ISSUE TITLE
[BUG] Don't switch to noise cancellation

### ISSUE THREAD

**Issue by dranivil** [ThePBone/GalaxyBudsClient#191]
This function just doesn't work from the app. When you turn noise cancellation on or off, it doesn't work. The last status that you put from the mobile always remains.

**Comment by ThePBone** [comment]
I can't reproduce this issue with the Buds Pro. Do you use Buds Live?
Keep in mind that noise cancellation won't be enabled if you only wear a single earbud.

**Comment by ThePBone** [comment]
Closed due to inactivity. Feel free to reopen if the issue persists.
