### ISSUE TITLE
Connection failed: Invalid parameter./매개 변수가 틀립니다.

### ISSUE THREAD

**Issue by AhnJaeHoon-0512** [ThePBone/GalaxyBudsClient#194]
I'm using the program while connecting to Buzz, but I can't use the program because of this error. It doesn't change even if you reinstall it.
And it says, "The provided device ID is not a valid Bluetooth Device."

ko-제가 버즈를 연결할려고 이 프로그램을 사용중인데요. 이게 매개 변수가 틀립니다. 라는 오류 메시지와 함께 아예 프로그램을 사용할수가 없습니다. 재설치해도 마찬가지이고요.
그리고 밑에 "제공된 디바이스 ID가 유효한 BluetoothDevice가 아닙니다."라고 적혀져 있네요. 무슨 조건인지는 모르겠으나 어떨 때는 오류메시지 없이 정상적으로 사용이 가능합니다.

**Comment by ThePBone** [comment]
Hey, 
please do the following steps:

1. Click on the "Options" button in the top-right corner. 
2. Select 'Unregister device' from the menu
3. When asked to select a new device, uncheck the "Use alternative Bluetooth backend" (this is important)
4. Now, select your device like normal and everything should work properly.

**Comment by AhnJaeHoon-0512** [comment]
> Hey,
> please do the following steps:
> 
> 1. Click on the "Options" button in the top-right corner.
> 2. Select 'Unregister device' from the menu
> 3. When asked to select a new device, uncheck the "Use alternative Bluetooth backend" (this is important)
> 4. Now, select your device like normal and everything should work properly.

Are you talking about program settings? Or are you talking about Windows settings? If it is a program setting, I am not even able to enter the program because of that error.

**Comment by cozyplanes** [comment]
> > Hey,
> > please do the following steps:
> > 
> > 1. Click on the "Options" button in the top-right corner.
> > 2. Select 'Unregister device' from the menu
> > 3. When asked to select a new device, uncheck the "Use alternative Bluetooth backend" (this is important)
> > 4. Now, select your device like normal and everything should work properly.
> 
> Are you talking about program settings? Or are you talking about Windows settings? If it is a program setting, I am not even able to enter the program because of that error.

Did you tried reinstalling the program?

**Comment by ArthurWolfhound** [comment]
@AhnJaeHoon-0512 try clearing contents of C:\Users\%userprofile%\AppData\Local\GalaxyBudsClient, that will reset the program.

@ThePBone as a side note - wiki is neglected, there's an old path there in clearing app cache.
P.S. Yes, I am back, not entirely but still. Uni is hell. Working on translation right now :)

**Comment by ThePBone** [comment]
@ArthurWolfhound Welcome back! I'll check and update the wiki.

**Comment by ArthurWolfhound** [comment]
@ThePBone also should've mentioned: for your consideration - official Werable warns about "Do not close your case while updating", think of adding this text to your firmware module? 

Also, where's the option for gray bud icons? Tried with dummies, didn't found that one... translated all nonetheless

**Comment by ThePBone** [comment]
@ArthurWolfhound Sure, I added it with commit https://github.com/ThePBone/GalaxyBudsClient/commit/0b0c9ac705430676cd4c1fda5b9d92f62c22e2c6#diff-c56492a88863e210c940ea7592cf880af0458b1306d31eabe1a78e5be7be3f20.

The icon option is part of the connection popup settings.

**Comment by ArthurWolfhound** [comment]
@AhnJaeHoon-0512 please respond with status about your problem, so we can check in on your progress or close the issue from your side, thank you.

**Comment by AhnJaeHoon-0512** [comment]
hello. First of all, I'm sorry I'm late. It's because I've been busy lately. Once the problem was initialized [C:\Users%userprofile%\AppData\Local\GalaxyBudsClient], it didn't work out, so I solved it by re-pairing, but I've had this problem before, so I'll have to watch it. Thank you for your answer!

KO-(It may not be accurate because English is translated by a translator.)안녕하세요. 일단 늦어서 죄송합니다.  요즘 좀 바쁜일이 있어서요. 일단 그 문제는 C:\Users%userprofile%\AppData\Local\GalaxyBudsClient 파일을 초기화 해도 해결이 안되어서 버즈를 재 페어링 하는것으로 해결되었긴 한데, 하지만 이전에도 재 페어링을 했는데도 다시 이런 상황이 발생하는경우가 있어서 한번 지켜봐야 할거 같아요. 답변 감사합니다!

**Comment by ThePBone** [comment]
Great, I'll mark this as resolved.
