### ISSUE TITLE
[Suggestion] Repackage and release on Windows Store

### ISSUE THREAD

**Issue by danperks** [ThePBone/GalaxyBudsClient#2]
This is the kind of program perfect for a cheap, paid release on the Windows Store. Repackage it to run as a UWP, and release it for £1.99 so you can get yourself the Buds+. 

I'd be happy to help with the conversion to UWP, not that I have much experience in it.

**Comment by ThePBone** [comment]
Yeah, thanks for the idea. I think I'll give it a try, I'm currently in the project validation phase and waiting for it to get approved. 👍

**Comment by superbonaci** [comment]
Does the Windows Store allow uninstall?
