### ISSUE TITLE
[REQ] Layout debug mode for translation.

### ISSUE THREAD

**Issue by cozyplanes** [ThePBone/GalaxyBudsClient#200]
**Is your feature request related to a problem? Please describe.**
A tool that can be a help when translating new fields.

**Describe the solution you'd like**
A debug tool deep in the settings that shows the different layout of each Buds versions (Buds, Buds+, Live, Pro).

**Describe alternatives you've considered**
Same as above.

**Additional context**
All features (dropdowns, slider, buttons) are enabled, but doesn't do anything. Just the frontend without the backend.

**Comment by ThePBone** [comment]
Hey, you can already do this by performing these steps:

1. Enable "Show dummy devices" and "Ignore translation loss" in the translator mode window.
2. Unregister your current device
3. When returned to the setup screen, there are now several dummy devices for all Buds models you can select in the device selection list.
4. Select one of these and you can trick the app to show the layout accordingly
