### ISSUE TITLE
Application does not start when clicked (v4.2)

### ISSUE THREAD

**Issue by Jasonxu5** [ThePBone/GalaxyBudsClient#207]
OS: Windows 10 Pro 64bit
Application Version: v4.2

I've looked into past issues such as #64 and tried deleting the `GalaxyBudsClient` folder in `%localappdata%` but the application still refuses to startup whenever I try to launch it. Reinstalling the application on the latest version also does not work as well.

**Comment by ThePBone** [comment]
Could you please post the `application.log` file in the `%localappdata%/GalaxyBudsClient` folder?

**Comment by Jasonxu5** [comment]
[application.log](https://github.com/ThePBone/GalaxyBudsClient/files/6417768/application.log)

Looking at the contents of the `application.log` file, I just realized that there is no `config.json` file in the directory
![image](https://user-images.githubusercontent.com/22270527/116934323-b07bdf00-ac19-11eb-8f99-7a9661a46fe3.png)

Since I can't even start up the application after reinstalling it, could the issue be that the `config.json` file is not being generated?

**Comment by ThePBone** [comment]
The application was terminated before it even had the chance to write a config file (and it is not necessary to have one either). Looking at the log file, there is no error or crash noted there. I also checked the anonymous crash reporting tool my app is connected to, and there are no reports of early crashes while starting up either.

This is rather strange; maybe there is more information about this in the Windows Event Viewer. Could you follow these steps and upload the exported events (if there are any) here: https://github.com/ThePBone/GalaxyBudsClient/issues/64#issuecomment-733276258

**Comment by Jasonxu5** [comment]
Here is the zip file
[GalaxyBudsClientEvent.zip](https://github.com/ThePBone/GalaxyBudsClient/files/6418041/GalaxyBudsClientEvent.zip)

One thing to note is that the event in the zip file occurred on 4/21/2021 where the application version was v4.1.1.1

When I attempt to start the application on the current version (v4.2), no events are generated.

**Comment by ThePBone** [comment]
Looks like the included .NET framework library files might be corrupt. 
Go to `%TEMP%\.net\Galaxy Buds Client` and delete all sub-directories in that folder (they contain parts of this app that are extracted for faster startup times, they'll get regenerated after the next launch). 
You can now re-run the app and maybe it'll work.

If it still doesn't work, you can try to install the latest Microsoft .NET framework 4.8 to (re)install to broken/missing libraries: https://dotnet.microsoft.com/download/dotnet-framework/net48

**Comment by Jasonxu5** [comment]
Disabling and re-enabling the .NET framework 4.8 runtime finally resolved the issue.

Thanks!

**Comment by ThePBone** [comment]
Great! I'll put this solution into the troubleshooting section in the releases tab.
