### ISSUE TITLE
[BUG] Battery type not specified

### ISSUE THREAD

**Issue by MollyBe** [ThePBone/GalaxyBudsClient#210]
`
`

I tried to follow the clearing application cache [instructions](https://github.com/ThePBone/GalaxyBudsClient/wiki/1.-Common-troubleshooting#clearing-application-cache) but the folder `%localappdata%\ThePBone_(Tim_Schneeberge` is missing.

In GBM - System - View System Information - Battery Type there is no battery information. Only the text `Not specified`.

I would expect to see battery information for the device here; headphones and case. This information is available in Samsung's Galaxy Buds Live android application.

![image](https://user-images.githubusercontent.com/51837460/117435546-45d6e600-af2e-11eb-8844-d26b2dbe5b52.png)

- OS: Windows 10 Pro 64bit 19042.928
- Application version: 4.2.0.0
- Device: Galaxy Buds Live

**Comment by ThePBone** [comment]
The battery information you can see in the official app is actually hardcoded and not retrieved from the earbuds itself.

**Comment by MollyBe** [comment]
Thanks, would it be worthwhile to include hardcoded battery information in system information?

**Comment by ThePBone** [comment]
Sure, I'll see whether I can find some space for it
