### ISSUE TITLE
[REQ] Mute Function

### ISSUE THREAD

**Issue by ntsour** [ThePBone/GalaxyBudsClient#217]
It would be great  if we had a mute function using touch controls during Teams/Zoom etc on a PC like we have during calls on a mobile device.

**Comment by ThePBone** [comment]
Since Windows Vista, programmatically manipulating any microphone properties has gotten much harder and requires access to the [Windows Core Audio APIs](https://docs.microsoft.com/en-us/windows/win32/coreaudio/core-audio-apis-in-windows-vista). However, to make proper use of them, I'd need to reference and bundle them (everything of them) with my app. That is a bit of an overkill for such a small addition that wouldn't even support other operating systems so I probably won't add it (at least not for Windows, Linux support for this would be very easy to implement).
The earbuds themselves don't have a software mic mute switch, so I can't send them a message over Bluetooth either.

The easiest way to solve this would be to use the hotkey custom action (check custom long-tap actions on the touchpad page) to trigger a special hotkey that mutes the mic in the voice app. Or alternatively, you could use the "Launch executable" custom touch action to launch a small batch script that triggers an external application that can handle the microphone mute toggle instead (using the command-line interface of [NirSoft's SoundVolumeView](https://www.nirsoft.net/articles/mute_microphone_command_line.html) for example).

**Comment by ntsour** [comment]
Thanks for your reply. About the workaround you propose. Is it a problem with my setup or is it normal for touch controls to not work during a Teams call? I tried to assign the shortcut to mute to the left long touch but it does nothing during a Teams call. It works when not in a call.

Thanks!

**Comment by ThePBone** [comment]
I never used the earbuds in a call before, but yeah, I think I heard someone complain about disabled touch controls while in a voice call some time ago. In that case, it's also impossible to make your original feature request work.

**Comment by ThePBone** [comment]
> "double-tap" action for volume also works on Windows during calls (perhaps a way to remap that?)

The double-tap action works differently than the normal touch actions. While I can detect these double-tap events, I cannot suppress the volume change that is triggered by them, which makes proper remapping impossible.

As far as remapping goes (apart from the customizable long-tap touch controls), I could only reliably remap single touch events by tricking the earbuds to enter a specific state (normally used for TTS notification readers). However, that is not available during a voice call either.

**Comment by eborn** [comment]
Hey, thanks for complete explanation.
I played a bit with the developer options you provided in the tool and looked what's happening on the bluetooth socket and definitely there is "something" specific being sent during long press (while being on the call). Would you be interested in taking a look at these dumps if I provided them?

**Comment by ThePBone** [comment]
Yeah, sure. You can upload them here

**Comment by ThePBone** [comment]
Here are some instructions on how to make this work using the 3rd-party tool I mentioned earlier. I wrote a little script that hooks into my app and updates the volume state of the earbuds microphone device in Windows (this won't toggle the mute button in your voice communication app, just in the Audio Control Panel of Windows). 

1. Download the 3rd-party tool by NirSoft and extract it: https://www.nirsoft.net/utils/soundvolumeview-x64.zip
2. Launch the program in the ZIP and make sure your earbuds are properly connected.
3. Find the Hands-free audio capture device provided by your earbuds. In my case, this is the right one:
![image](https://user-images.githubusercontent.com/38386967/118001835-6399b600-b347-11eb-978d-6f566a860e47.png)
4. Right-click the correct row and select "Copy item ID"

5. Now download my pre-made script, you'll need to modify it a bit:
[TouchEventHook.zip](https://github.com/ThePBone/GalaxyBudsClient/files/6467267/TouchEventHook.zip)

6. Open the .cs file and go to line 10 and 11:
```c#
private const string SoundVolumeViewPath = @"D:\soundvolumeview-x64\SoundVolumeView.exe";
private const string TargetDeviceId = @"{0.0.1.00000000}.{93eb5492-7923-4b5e-825b-bfc2fd63dfab}";
```
Replace the path to `SoundVolumeView.exe` with the correct one for your system and update `TargetDeviceId` to the item id you've just copied using the utility. 
(Make sure to keep the syntax around the values as-is: ` = @"insert your customized value here"`)

7. Press `Win+R` on your keyboard and insert `%localappdata%/GalaxyBudsClient/scripts` into the run box and hit Enter.
8. A folder will open and you can just place the modified .cs-file into it.
9. Fully restart the GalaxyBudsClient to load the script properly (make sure the icon in the tray bar is completely gone).
10. If everything went alright and the GalaxyBudsClient is properly connected to your earbuds, it should now toggle the mute state of the microphone device you've selected earlier when you **long-press your right earbud**.

You can verify if it works by opening the SoundVolumeView program and observing  the mute state of the microphone.

**Comment by ntsour** [comment]
Thanks a lot for the workaround!

I tried it but the right earbud long-press still does the previously assigned function.

Do  I need to change something in the configuration of the application  and assign the right long-press to something else, or I am doing something else wrong. Is it suppsoed to load the script automatically and override whatever configuration you have for the right long-press if done correctly?

Cheers!

**Comment by ntsour** [comment]
To answer my own question... it works automatically if the script is done right.

It works! 

Thanks a lot Tim!!!!!

Really appreciate it.

 Don't need those Jabra then, even if they do it a little bit better.

**Comment by ThePBone** [comment]
It is not able to override the existing touch action, to only adds an additional trigger.
You can choose a touch action on the touchpad page in the app that is not supported on Windows, to work around this. For example, select "Spotify (Android only)" as the touch action for the right touchpad. 

It is loaded automatically. You can press "Win+R" and run `notepad %localappdata%/GalaxyBudsClient/application.log` to look at the application log to check whether it loaded properly (search for `[INF] TouchEventHook is ready`).

**Comment by ThePBone** [comment]
@ntsour Great!

**Comment by ntsour** [comment]
As a side note. 

You can have ambient sound toggle on-off at the same time. 

So you know when you are muted!

Neat!

**Comment by ThePBone** [comment]
If you want to check whether you are muted or not, you can also fall back to the SoundVolumeView program.

Also, here are some additional parameters that can be changed in the script file to change which touch gestures it should respond to.
Again, keep in mind that I can't suppress the original touch action (single touches will still emit play/pause commands to the PC and so on):

Line 13, change whether the left or right touchpad should trigger it:
```c#
private const DeviceInv TouchpadSide = DeviceInv.R;
```
Replace `DeviceInv.R` with `DeviceInv.L` to monitor the left touchpad instead.

____

Line 14, change which touchpad gesture triggers the action:
```
private const byte TouchpadEventCode = 0x04;
```
Replace 0x04 with any of these values: (tested with a pair of Buds Pro)

| Value | Description                                                              |
|-------|--------------------------------------------------------------------------|
| 0x01  | Single touch                                                             |
| 0x02  | Double touch                                                             |
| 0x03  | Triple touch                                                             |
| 0x04  | Tap and hold (short)                                                     |
| 0x05  | Tap and hold (normal)                                                    |
| 0x07  | Tap and hold (long; warning: repeats multiple times if held down longer) |
| 0x09  | Edge double-tap volume controls                                          |

**Comment by ntsour** [comment]
For some reason that I cannot identify, today this functionality stopped working.

When in a call, tap and hold no longer registers any action .

Any pointers at to what could be failing? Could be the Galaxy Buds Manager App? Windows? A configuration on the buds? The Bluetooth stack?

Thanks!

**Comment by ntsour** [comment]
> For some reason that I cannot identify, today this functionality stopped working.
> 
> When in a call, tap and hold no longer registers any action .
> 
> Any pointers at to what could be failing? Could be the Galaxy Buds Manager App? Windows? A configuration on the buds? The Bluetooth stack?
> 
> Thanks!

My mistake again. I had repaired the buds and obviously the ID needed to change.

**Comment by ntsour** [comment]
> If you want to check whether you are muted or not, you can also fall back to the SoundVolumeView program.
> 
> Also, here are some additional parameters that can be changed in the script file to change which touch gestures it should respond to.
> Again, keep in mind that I can't suppress the original touch action (single touches will still emit play/pause commands to the PC and so on):
> 
> Line 13, change whether the left or right touchpad should trigger it:
> 
> ```cs
> private const DeviceInv TouchpadSide = DeviceInv.R;
> ```
> 
> Replace `DeviceInv.R` with `DeviceInv.L` to monitor the left touchpad instead.
> 
> Line 14, change which touchpad gesture triggers the action:
> 
> ```cs
> private const byte TouchpadEventCode = 0x04;
> ```
> 
> Replace 0x04 with any of these values: (tested with a pair of Buds Pro)
> 
> Value	Description
> 0x01	Single touch
> 0x02	Double touch
> 0x03	Triple touch
> 0x04	Tap and hold (short)
> 0x05	Tap and hold (normal)
> 0x07	Tap and hold (long; warning: repeats multiple times if held down longer)
> 0x09	Edge double-tap volume controls

Hi Time. First of all thank you for this solution. I am using it already everyday.

Is there by chance any command we could put in the script to make the bud beep or something when the mute is on?

**Comment by ThePBone** [comment]
If the earbuds won't do it themselves, we need to handle it inside the script as well.

I extracted the sound files from the firmware packages a while ago, so we can reuse the official 'tap sound'.

Extract this audio file somewhere on your computer: 
[BudsPro_TapSound.zip](https://github.com/ThePBone/GalaxyBudsClient/files/6495539/BudsPro_TapSound.zip)


Around line 21/22 in the script file replace:
```c#
	private static void TriggerAction()
	{
```
With:
```c#
	private static void TriggerAction()
	{
	    System.Media.SoundPlayer player = new System.Media.SoundPlayer();
	    player.SoundLocation = @"C:\R190XXU0AUD5_0x13119e.wav";
	    player.Load();
	    player.Play();
		
```

Of course, you need to replace `C:\R190XXU0AUD5_0x13119e.wav` with the correct path to the audio file you've extracted earlier.

This will only play a sound when the mute state has been toggled. I cannot easily implement a reliable continuous sound while mute is on.

**Comment by ntsour** [comment]
Thanks!!! I got it to work outside a call but when in a call it won't play. I do see the entry in the debug log, so the method is indeed called after the edit. But the .wav won't sound, although the mute toggle does work. Outside a call it sounds ok and toggles the mute.

Sorry to bother you with this. again. If you have any more ideas about what to try it will be highly appreciated.

Cheers.

**Comment by ThePBone** [comment]
Oh right, I forgot that while in a call, the earbuds switch to another Bluetooth profile called 'HFP' (with lower quality) to enable a two-way audio stream for the microphone audio. While in this mode, the voice chat application takes full exclusive access over the audio stream, so any sounds played by other apps will either go into nowhere or to your secondary speakers. 

More details: https://superuser.com/questions/1164714/cant-hear-other-programs-sound-when-using-bluetooth-headsets-with-voice-chat-a

In this case, I really can't do anything about it. Of course, you could forcefully [disable the HFP profile](https://superuser.com/a/925585/1070086), but you will also be unable to use the microphone on the earbuds.

**Comment by ArlindoFNeto** [comment]
Hello guys,

Is there any plans to insert this feature in a future version (even that experimental)? I use ArchLinux and had no luck until now to mute mic by touchpad actions (in all system by script) during HFP profile.
