### ISSUE TITLE
[REQ]Please provide more old version firmware

### ISSUE THREAD

**Issue by gq7123** [ThePBone/GalaxyBudsClient#218]
I have Buds Pro connected to my PC. I want to try the previous version，like aua1，atl9. But Only 2 latest versions are available in the software. Please provide more old version firmware. Thanks!
Firmware downgrading is a good feature.

**Comment by ThePBone** [comment]
Unfortunately, I don't have other old firmware backed up since I only started scraping Buds Pro firmware files starting last month.

Because Samsung only stores the latest firmware version on their update servers, I cannot retrieve older versions released in the past.

**Comment by gq7123** [comment]
Is there any way to extract the old version from the headset?

**Comment by ThePBone** [comment]
No, update packages are immediately deleted from the earbuds after the update.
Once the firmware has been flashed onto the earbuds, you won't be able to reconstruct a valid firmware update binary, even if you have full access to the memory chip.

**Comment by ThePBone** [comment]
However, the last downloaded firmware update is always stored in the internal app data directory of the Buds Pro app.
If your friend has a **rooted**  Android device with the app installed and hasn't downloaded a new update yet, he may be able to access the old update in that directory.

Again, this requires root permissions to access this folder: /data/data/com.samsung.accessory.atticmgr
