### ISSUE TITLE
[REQ] Display popup when case opened

### ISSUE THREAD

**Issue by MollyBe** [ThePBone/GalaxyBudsClient#225]
When I open the case (without the headphones inside) I would like the popup to be displayed. 

I suspect it is impossible to know when the case is opened unless the headphones are inside them though?

**Comment by ThePBone** [comment]
Yes, it is only possible to know whether an earbud is in the case or not.

The case has no Bluetooth connectivity whatsoever. Even the battery percentage of the case can only be measured by the earbuds when at least one of them is inserted, and the case is open.
