### ISSUE TITLE
Just asking a question

### ISSUE THREAD

**Issue by schalldemz** [ThePBone/GalaxyBudsClient#226]
How could I make the seamless connection work properly? I did it when the first time I use this program just like the airpods does on iOS and iPadOS. But after that, I have not done that 'seamless' cause I have to open the Wearable than it will connect to my phone. Therefore, I do not know what I did wrong on any point though.

By the way, I really like the pop-up, thank you for bringing me that feature on PC and I could get better connection process experience on that.

**Comment by ArthurWolfhound** [comment]
(Contributor here) I may be wrong, but seamless connecrion might only work on Samsung Devices...


BTW, there's a new discussion feature so anyone can talk there without opening issues.

P.S.: I will convert that into discussion shortly.

**Comment by schalldemz** [comment]
It just seems to be with that feature but not able to work well all the time which means that it is not connected without retry several time on the PC. But the PC, while playing new media, is trying to connect the Buds and it is failed most of time.
And I just made it again.
Idk, probably the issue is on the phone
