### ISSUE TITLE
[REQ] Show CODEC info in-app

### ISSUE THREAD

**Issue by cozyplanes** [ThePBone/GalaxyBudsClient#243]
Like Bluetooth Tweaker (https://avxhm.is/software/Bluetooth.Tweaker.1.1.2.1.html)
Since Windows 11 is going to support AAC codecs, maybe a small label that shows the current connected codec may be nice.

![101396a4d72640d6b8de333d695e0d2d](https://user-images.githubusercontent.com/25971070/124350785-a6825680-dc31-11eb-8608-3c750674d43f.png)

**Comment by ThePBone** [comment]
I can't implement this due to technical/financial reasons. More info here: https://github.com/ThePBone/GalaxyBudsClient/issues/209#issuecomment-852377124
