### ISSUE TITLE
[REQ] Fix PKGBUILD for Arch-based distributions

### ISSUE THREAD

**Issue by rcht** [ThePBone/GalaxyBudsClient#250]
The PKGBUILD is broken and it's been unsolved for about a month, just a suggestion

**Comment by ThePBone** [comment]
To be fair, I only submitted the package 12 days ago. 😄  

Sorry, but I don't have too much time to spend on this at the moment. I haven't been actively using Linux or Arch for months anyway, which causes me to respond to Linux-related (installation) issues even slower, so I've decided to drop the package and unlink automatic binary uploads via GitHub Actions. 

The package is currently in a 'disowned' state, so anyone can adopt it if he/she wants to.
