### ISSUE TITLE
[BUG] Live Buds Software Downgrade Problem

### ISSUE THREAD

**Issue by EgeK2** [ThePBone/GalaxyBudsClient#256]
When i downgrade Live buds left one does not downgrading only right but downgrading. I also checked if both are paired and tried again several times but everytime only right bud downgraded.

**Comment by EgeK2** [comment]
[application.log](https://github.com/ThePBone/GalaxyBudsClient/files/6986826/application.log)

**Comment by ThePBone** [comment]
The log files look normal, the update is copied properly to the earbuds.
This seems to be an issue with the Buds themselves.

To bring both earbuds back to the same version, try to re-flash the firmware again. If this still fails use the official app to reflash.
