### ISSUE TITLE
[BUG] Terminal is visible and can't be closed without closing the program 

### ISSUE THREAD

**Issue by RafaelSchridi** [ThePBone/GalaxyBudsClient#259]
**Describe the bug**  
Updated and now the a terminal opens with the program

**Screenshots**  
![Galaxy_Buds_Client_2021-08-29_04-15-06](https://user-images.githubusercontent.com/11460682/131248299-66ff8a85-09d8-4c9c-8a15-96950220ca1a.png)

**Desktop (please complete the following information):**  
 - OS: Windows 11 Beta
 - Application version: 4.3

**Log files**  
[application.log](https://github.com/ThePBone/GalaxyBudsClient/files/7072348/application.log)

**Comment by AlamosIT** [comment]
I noticed the same issue

**Comment by ThePBone** [comment]
Thanks for reporting the issue. I published a new version with a bugfix for this here: https://github.com/ThePBone/GalaxyBudsClient/releases/tag/4.3.1
