### ISSUE TITLE
Galaxy Buds Live Unsupported

### ISSUE THREAD

**Issue by nyr3188** [ThePBone/GalaxyBudsClient#27]
The Galaxy Buds Live are unsupported. When I try to connect the app to them, it suggests that they are regular Galaxy Buds and doesn't work.

**Comment by ThePBone** [comment]
Whoops, I forgot to blacklist them.
Galaxy Buds Live are unsupported and will probably never receive support, unless someone who owns them adds them to this app.

**Comment by ThePBone** [comment]
Commit 88904b8372e78f4dc247380d6903535d31b4549e adds an error message when attempting to connect to Galaxy Buds Live.

**Comment by rnarenti** [comment]
Hi ThePBone i'm owner of Galaxy Buds Live, i would like to help to add it to this software, what can I do to help?
