### ISSUE TITLE
[BUGWhen I use the software, the Bluetooth connection of the system will become very late, and I do not use the Bluetooth system of the software, right. My model is galaxy buds2.

### ISSUE THREAD

**Issue by zhuluojun99** [ThePBone/GalaxyBudsClient#270]
**Describe the bug**  
A clear and concise description of what the bug is. Examples are: can't connect. unexpected behaviour

**To Reproduce**  

**Expected behavior**  

**Screenshots**  

**Desktop (please complete the following information):**  
 - OS: Windows 7/8/8.1/10 [Home / Pro] [32bit / 64bit] OS Build number, default system language 
 
 - Application version: 

**Additional context**  

**Log files**  
In most cases if you have a bug, log file will be required - it is located at ```%localappdata%\GalaxyBudsClient\application.log```

**Comment by ThePBone** [comment]
I'm not sure what you mean, please fill out the issue template properly next time.

If you have problems with the Bluetooth connection try to do the following:
1. Unregister your earbuds in the app if not already done, like this: `Options > Unregister device`
2. Proceed to the device selection page
3. **Disable the switch with the label 'Use alternative Bluetooth backend'**
4. Select your earbuds from the list and continue
