### ISSUE TITLE
[REQ] Add support for touch control toggles

### ISSUE THREAD

**Issue by githubcatw** [ThePBone/GalaxyBudsClient#273]
The Galaxy Buds2 (and likely the Buds Pro too) have a setting for disabling specific touch controls or all of them:
![image](https://user-images.githubusercontent.com/17374742/134764681-6b39867d-bd14-407e-b747-671fd0053e30.png)

I captured dumps as well. I toggled every toggle here off and on, opened Galaxy Buds Manager and downloaded a dump. I can send it on Telegram.

**Comment by ThePBone** [comment]
I added it. However, it's untested because only the Buds2 support this feature, and I don't own a pair.
https://github.com/ThePBone/GalaxyBudsClient/releases/tag/4.4

**Comment by githubcatw** [comment]
Thanks, will check tomorrow.

**Comment by githubcatw** [comment]
Touch controls and ambient sound customization work fine.
