### ISSUE TITLE
[BUG] ANC mode selection doesn't stick

### ISSUE THREAD

**Issue by geraldbrent1** [ThePBone/GalaxyBudsClient#276]
**Describe the bug**  
Buds Pro behavior for switching ANC modes doesn't stick after connecting to another device

**To Reproduce**  
Change noise control switching mode to ANC, Ambient, Off in the GUI, connect to another device.

**Expected behavior**  
Expected behavior is for the 3 modes to be the behavior on other devices. Only ANC and Ambient work once disconnected from my computer running Galaxy Buds Manager.

**Desktop :**  
 - OS: Windows 11 Education OS Build 21H2, English 

 - Application version: 
 -  4.4.0.0

**Log files**  

[application.log](https://github.com/ThePBone/GalaxyBudsClient/files/7319728/application.log)

**Comment by ThePBone** [comment]
I think this is a bug on Samsung's side. The 'ANC, Ambient, Off' switching mode is an unused feature in the firmware of the Buds and seems to be buggy. Their official apps also seem to reset that setting.
