### ISSUE TITLE
[BUG] In app updater does not work

### ISSUE THREAD

**Issue by Pratik-193** [ThePBone/GalaxyBudsClient#277]
**Describe the bug**  
When trying to update the app using in-app updater, i get errror - Download failed Reason: The SSL connection could not be established, see inner exception. The remote certificate is invalid according to validation procedure

**To Reproduce**  
Click options on top left, click check for updates, install now

**Expected behavior**  
the app should be updated to latest version

**Desktop (please complete the following information):**  
 - OS: Windows 10 20H2

**Comment by Pratik-193** [comment]
Is someone looking into this? See no response since a month now.

**Comment by ThePBone** [comment]
Closing, since the in-app updater has been out-of-use for a long time. It'll probably be removed in a future update.
