### ISSUE TITLE
[BUG] UI stops updating on Windows 11

### ISSUE THREAD

**Issue by RafaelSchridi** [ThePBone/GalaxyBudsClient#286]
**Describe the bug**  
After a while the UI just freezes, it looks normal and you can interact with it, but nothing actually works.

**Steps To Reproduce**  
Don't really have any, just happens randomly.

**Expected behavior**  
Even if theres an error I kinda expected "refresh dashboard" to fix it but that also doesn't work.

**Screenshots**  
![image](https://user-images.githubusercontent.com/11460682/141210163-d67bfe8c-3f53-496a-928d-1be46d38c6d3.png)
In the screenshot I have the buds closed in the case and disconnected, but it still shows it connected and even that I'm wearing one.

**Desktop:**  
 - OS:  Windows 11 Build 22000.282
 - Application version: v4.4.1 & 4.2.1 (tried other 4,2,1 just to check if it was OS related.)

**Additional context**  

**Log files**  
My log file is massive, and might be over multiple versions:
[application.log](https://github.com/ThePBone/GalaxyBudsClient/files/7516560/application.log)

There one thing that always stands out while also being the last line:
```log
[ERR] Windows.BluetoothService: BluetoothServiceLoop: IOException thrown while writing to socket: Unable to write data to the transport connection: An established connection was aborted by the software in your host machine... Cancelled.
```

**Comment by ThePBone** [comment]
It appears that the legacy Bluetooth backend was selected (Windows 7 and up; unstable with some Bluetooth adapters) instead of the new one for Windows 10 and later.

To fix this you could try to do this:
1. Options > Unregister device
2. Select your device 
3. On the bottom of the same page, enable the 'Use alternative Bluetooth backend' switch

**Comment by RCAPSN** [comment]
Me too meet the similar bug. 

OS: Windows 11 Build 22000.318
Application version: v4.4.1

The app can't get any data feedback from Galaxy Bud+ in Win11

![2021-11-16_143527](https://user-images.githubusercontent.com/94433090/141934110-55243b0e-13ee-4248-b3a6-bd2c733c6d41.jpg)
![2021-11-16_143541](https://user-images.githubusercontent.com/94433090/141934118-f5f65789-0cf1-4056-9e06-cd298e9dd275.jpg)

**Comment by RafaelSchridi** [comment]
Using the alternative backend for the past few days and have had no issues yet.
