### ISSUE TITLE
one bud input one bud output[REQ]

### ISSUE THREAD

**Issue by roeravid** [ThePBone/GalaxyBudsClient#291]
**Is your feature request related to a problem? Please describe.**
So this isn't exactly a problem that requires solving, this is just a highly extraneous and particular request. The purposes for which I would use it personally are to listen to beats in one ear and freestyle in the other so that in theory I could transcribe my freestyles while also listening to beats. Thanks so much! This whole project is awesome and so are you
**Describe the solution you'd like**
 if there's some way to separate each bud and make one only using the mic and one only outputting audio, that would be an amazing feature. 
**Describe alternatives you've considered**
Of course this is again a highly unnecessary feature, obviously I can use another device to listen and transcribe on my phone but if I'm not next to my computer it would be nice to be able to do it on the go. So to be clear in terms of alternatives, this feature would be the alternative to what is already the standard.
**Additional context**
None, just wanted to say again thanks so much for being awesome! I'm currently learning to code online so hopefully soon I'll be able to contribute myself! Best!

**Comment by alba4k** [comment]
Here I am, 2 years after this was opened

I don't think that this should be part of this specific program, as it is not directly related to galaxy buds.

Something that you might try, though, would be to configure your left-right balance to only send audio to a specific earbud by pushing the slider to one side (on Windows, Settings > Sound > [Your device] > Properties > Balance; if I recall correctly). I'm not sure on how the microphone is managed though, but this alone should give a decent result :)

**Comment by ThePBone** [comment]
This would require decoupling both earbuds. Samsung has software that can de-/re-couple single earbuds for their repair centres, but I don't know how to unlock that functionality.
