### ISSUE TITLE
[BUG] RTL Layout not supported

### ISSUE THREAD

**Issue by RisinT96** [ThePBone/GalaxyBudsClient#292]
**Describe the bug**  
App is written with LTR layout in mind, doesn't properly work in RTL languages, like Hebrew or Arabic.
as a reault all the translations have to be written in reverse order of words, and it gets even worse if the text is long and gets stretched over multiple lines, the bottom lines include text that should've been on top.

You can check the hebrew translation (run it through google translate), all the text is written backwards.

**To Reproduce**  
* Switch app to an RTL language.

**Expected behavior**  
The text should be properly rendered out in RTL layout.

**Desktop (please complete the following information):**  
 - OS: Windows 10 Pro 64bit 19043.1415, EN-US
 - Application version: 4.4.1

I don't have much experience in C#, but I'm willing to try to fix this myself.

**Comment by ThePBone** [comment]
Fixed with https://github.com/ThePBone/GalaxyBudsClient/commit/eee4cffaffee5b9a79cf679b6879868861c1420f
