### ISSUE TITLE
V1.2.0 starts and shuts down immediatly

### ISSUE THREAD

**Issue by jouke1998** [ThePBone/GalaxyBudsClient#3]
Thanks for the amazing program! Only one issue. After performing the update from 1.1.0 the program does not start normally anymore, after starting it immediatly shuts down. I cant even see the window pop up. Also after reinstalling the problem is not solved. V1.1.0 worked perfectly.

**Comment by ThePBone** [comment]
I think I know what happened there. 1.2.0 adds a new feature with works only with the new firmware R170XX0ATF5. It seems to break compatibility with the older ones.

And the reason why downgrading didn't work is that the installer will only replace older files with newer ones and not the other way around, so you would need to fully uninstall it before reinstalling 1.1.0.

You can easily solve this issue by updating the firmware of your Buds or wait until I've a fix ready

**Comment by ThePBone** [comment]
This update should fix this issue: https://github.com/ThePBone/GalaxyBudsClient/releases/tag/1.2.1

**Comment by jouke1998** [comment]
This indeed fixed the issue! Thank you very much for the quick fix!
