### ISSUE TITLE
How to downgrade firmware of galaxy Buds pro?

### ISSUE THREAD

**Issue by knadityas92** [ThePBone/GalaxyBudsClient#306]
Is there any way to downgrade the firmware version of galaxy buds pro? I have one serious issue after the firmware update. It doesn't always occurs. Issue is sometimes either one of the bud simply turns off by itself and doesn't turn on until I put them back in the case and again need to put in my ears to start listening. So I thought it would be the issue with firmware.

**Comment by ThePBone** [comment]
Yes, that's possible with this app:

1. Navigate to 'Advanced > Firmware updates'
2. Enable the 'Allow firmware downgrade' toggle on the bottom
3. Select a firmware version to install from the list
