### ISSUE TITLE
my galaxy pods dont connect

### ISSUE THREAD

**Issue by Billybobertjoe** [ThePBone/GalaxyBudsClient#308]
i have a pair of galaxy pods gear IconX which dont connect. i paid for the software from the microsoft store.

**Comment by ThePBone** [comment]
>i paid for the software from the microsoft store.

**I'm not selling my software on the Microsoft Store!!** This app is available for free on this GitHub page! Also, this app does not support IconX Buds. 

### The publisher on the Microsoft Store is a scammer who stole my application and is selling it for money without my authorization!
Try to refund the purchase or contact Microsoft Store support to get your money back.

I've sent a DMCA claim to Microsoft to get the app removed from the store as fast as possible.

**Comment by Billybobertjoe** [comment]
refunded :)

**Comment by Billybobertjoe** [comment]
Will you be able to add support for iconX buds?

**Comment by ThePBone** [comment]
@Billybobertjoe
Probably not. I don't own a pair of IconX and they are too different from the Galaxy Buds series that I could try to implement it without having a device to test on.
