### ISSUE TITLE
Can't connect to my Galaxy buds Pro

### ISSUE THREAD

**Issue by CanisZhang** [ThePBone/GalaxyBudsClient#312]
Pairing is possible, but the main interface always looks like this
![image](https://user-images.githubusercontent.com/60993363/156877120-feb18a3d-fafe-4b99-9d2f-1505a34dcba4.png)

**Comment by CanisZhang** [comment]
After I switch to version 4.1.1, it tell me unable to establish connection.
![image](https://user-images.githubusercontent.com/60993363/156885591-1fe21098-b503-4416-be7f-5e48dc249068.png)

**Comment by mirco261** [comment]
Hi, I have same problem with my samsung buds pro... 
Maybe we have same problem - I see that I dont have any information about serial number and others info... 
Have anyone idea what to do ? 

thank you all
![275933796_4946373708784687_3295361727004123575_n](https://user-images.githubusercontent.com/20154835/158893052-21445712-5e69-41cd-9850-a9112ac9f3ab.jpg)

**Comment by CanisZhang** [comment]
> Hi, I have same problem with my samsung buds pro... Maybe we have same problem - I see that I dont have any information about serial number and others info... Have anyone idea what to do ?
> 
> thank you all ![275933796_4946373708784687_3295361727004123575_n](https://user-images.githubusercontent.com/20154835/158893052-21445712-5e69-41cd-9850-a9112ac9f3ab.jpg)

I can use it normally after upgrading win11. I guess it's a bug in win10

**Comment by alba4k** [comment]
By any chance, could they have been fake? or did it just fix itself with some time (in that case, this issue can be closed, I believe?)

**Comment by mirco261** [comment]
Mine Buds was fake... :( So, this app works well with official samsung buds...

**Comment by alba4k** [comment]
well... yes, since fake ones don't have the same features, nor communicate in the same way
