### ISSUE TITLE
[CRSH] Cannot launch application from AUR package on Arch Linux

### ISSUE THREAD

**Issue by rensenware** [ThePBone/GalaxyBudsClient#314]
**Shortly describe what were you doing before crash**
 - Simply launched program from command line. 

**Include event files here**
[Pastebin with error information.](https://hastebin.skyra.pw/sugocajuru.wren) 

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Application version: 4.4.1-3, Installed from AUR
 - Packages matching the label 'ICU' on system - harfbuzz-icu version 4.2.0-3, icu version 71.1-1, lib32-icu version 71.1-1

**Additional context**
The package previously worked before. I think that the icu update to version 71.1-1 in a recent pacman update broke this program. It probably just needs to be updated to work with the new component.

**Comment by rensenware** [comment]
This also seems to happen when attempting to run the program from the portable .bin file in the github releases.

**Comment by rensenware** [comment]
And as I thought, downgrading icu to version 70.1-1 fixes the issue at the cost of most every other program on the system.

**Comment by rezanmz** [comment]
Same issue

**Comment by smvd** [comment]
Is there a way to fix it without breaking most of the system by downgrading the icu?

**Comment by ThePBone** [comment]
I'll look into it tomorrow. Recompiling the app might already be enough. Maybe I'll need to upgrade the .NET framework to the latest version as well.

**Comment by luisbedoia** [comment]
same issue, this is my solution:
run this in the terminal
`export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 && galaxybudsclient`

**Comment by ThePBone** [comment]
I've upgraded the app from NET Core 3.1 to NET 6. NET 6 should have proper support for the newer ICU packages; same for libssl.

You can grab precompiled binaries here: https://github.com/ThePBone/GalaxyBudsClient/actions/runs/2282369073 (scroll all the way down)

**Comment by rensenware** [comment]
Thank you!

**Comment by ThePBone** [comment]
I accidentally left some debug code in the previous binary that would suppress all disconnection events and prevent the app from reconnecting properly (it thinks there are always earbuds connected).

Here's an updated version: https://github.com/ThePBone/GalaxyBudsClient/actions/runs/2296295533
I'll publish a stable update soon as well.
