### ISSUE TITLE
[BUG] No usable version of libssl was found

### ISSUE THREAD

**Issue by helkaluin** [ThePBone/GalaxyBudsClient#319]
`libssl1.1` is no longer in the repos as of Ubuntu 22.04. It seems [dotnet 6+ starts supporting OpenSSL 3](https://github.com/dotnet/core/issues/7038#issuecomment-1110377345), and I know you've recently bumped the dotnet version to 6.0.200 (https://github.com/ThePBone/GalaxyBudsClient/commit/fd6a642d0d68b289d437af7641cd5dd48f3982b4), but the binaries from Github releases still throw a `No usable version of libssl was found` error.

Could you perhaps try a more recent version?

**Comment by ThePBone** [comment]
I've upgraded the app from NET Core 3.1 to NET 6.

You can grab precompiled binaries here: [ThePBone/GalaxyBudsClient/actions/runs/2282369073](https://github.com/ThePBone/GalaxyBudsClient/actions/runs/2282369073) (scroll all the way down)

**Comment by helkaluin** [comment]
You're far too quick haha. This is great.

Though the libssl error is now gone, it throws a new exception about not being able to load libSkiaSharp. Do you want me to open a new bug?

**Comment by ThePBone** [comment]
Apparently, NET 6 doesn't include native libraries in self-contained single-file builds anymore by default. 

Updated binaries: https://github.com/ThePBone/GalaxyBudsClient/actions/runs/2294988386

**Comment by helkaluin** [comment]
Heya. It all works now. Many thanks!
