### ISSUE TITLE
[REQ] Galaxy Buds2 Support

### ISSUE THREAD

**Issue by cybooo** [ThePBone/GalaxyBudsClient#326]
Is there any support for the Buds2 at all? Yes, I know this was already requested, but the issue I found is almost a year old. Are there any recent beta builds that support the Buds2, or was the support dropped? I have a pair on me and I would love to use this app.

**Comment by ThePBone** [comment]
The Buds2 have been supported since last August (v4.3).
I don't own a pair myself, so I had to implement support without testing on my own, but according to users with Buds2, the earbuds work correctly with this app.

**Comment by cybooo** [comment]
I did download the latest version. I paired and connected my Buds2, but the app just can't find them, even if i disable or enable the alternative Bluetooth backend. Nothing.

**Comment by JordyEGNL** [comment]
> I did download the latest version. I paired and connected my Buds2 with Bluetooth, but the app just can't find them, even if i disable or enable the alternative Bluetooth backend. Nothing.

Same for my pair of Buds2. Connected via Bluetooth but the app cannot find them

**Comment by ThePBone** [comment]
Could you tell me the device name the earbuds show in Windows? This app tries to detect the model of the earbuds using that name.

**Comment by JordyEGNL** [comment]
> Could you tell me the device name the earbuds show in Windows? This app tries to detect the model of the earbuds using that name.

For me it's **Jordy's Buds2**

**Comment by ThePBone** [comment]
That explains it. The device name used to be static like `Galaxy Buds2 (....)` where .... would be a part of the MAC address.

You can grab updated binaries here: https://github.com/ThePBone/GalaxyBudsClient/actions/runs/2363100060 

It could take about 8 minutes until the downloads are ready and visible.

**Comment by JordyEGNL** [comment]
> That explains it. The device name used to be static like `Galaxy Buds2 (....)` where .... would be a part of the MAC address.

Yep it is still that for my original Galaxy Buds

> You can grab updated binaries here: https://github.com/ThePBone/GalaxyBudsClient/actions/runs/2363100060

Thanks! Will check

**Comment by JordyEGNL** [comment]
It seems to be working now! I had my old Galaxy Buds still connected so I unregistered it and tried again, working fine now. Thank you
