### ISSUE TITLE
Can't find "minimize to tray" and "launch on boot" under Options

### ISSUE THREAD

**Issue by obrobrio2000** [ThePBone/GalaxyBudsClient#328]
I can't seem to find "minimize to tray" and "launch on boot" under Options. I tried installing the latest release from winget (4.5.1) and I also tried installing the latest release downloaded from github (4.5.2). I also tried uninstalling (cleaning all the leftovers) and reinstalling. The minimize to tray seems to be working if I click once on the tray icon, but I still can't find the "launch on boot" option. I even checked under task manager ("startup apps" section") or under task scheduler to see if there was a task scheduled at startup: nothing found in both cases. How can I make it start at boot (minimized in tray)?

Left: illustration on github / Right: client installed on my laptop
![Screenshot (56)](https://user-images.githubusercontent.com/62136803/169667349-3d3b1d65-a554-4533-acdb-4b260e67ee80.png)

**Comment by ThePBone** [comment]
This was caused by an incorrect OS check.

You can grab updated binaries here:
https://github.com/ThePBone/GalaxyBudsClient/actions/runs/2366081081
I haven't had the chance to test them on Windows yet, but they should work fine.

**Comment by obrobrio2000** [comment]
> This was caused by an incorrect OS check.
> 
> You can grab updated binaries here: https://github.com/ThePBone/GalaxyBudsClient/actions/runs/2366081081 I haven't had the chance to test them on Windows yet, but they should work fine.

Thanks, it all works perfectly now!
