### ISSUE TITLE
[BUG] The application started only once

### ISSUE THREAD

**Issue by WBApplication** [ThePBone/GalaxyBudsClient#330]
**Describe the bug**  
The application launches only once. I recently downloaded and installed the app, opened it and connected to the Buds2 headphones, once I was done using the headphones I closed the app and put the headphones in the case. Now I want to run the app again but I can't!
When I click the app icon nothing happens. The application appears in task manager for maybe two seconds and then closes itself.

I have already reset the computer and reinstalled the application but it does not help

**To Reproduce**  
1. Install App
2. Open App
3. Connect Buds2
4. Close app, put headphones into case
5. Turn PC into sleep mode (laptop) and turn on again, try open the app

**Expected behavior**  
running application

**Desktop (please complete the following information):**  
 - OS: Windows 11 21H2 22000.675
 - Application version: 4.5.2

**Log files**  
Per unsuccessful run only this line is added to log file
`2022-05-28 12:11:57.077 +02:00 [INF] Using settings file at: C:\Users\hesam\AppData\Local/GalaxyBudsClient/config.json`

**Comment by ThePBone** [comment]
This bug should be fixed in the [latest version](https://github.com/ThePBone/GalaxyBudsClient/releases).

See https://github.com/ThePBone/GalaxyBudsClient/issues/314 for details.

**Comment by suwagawaki** [comment]
I experienced this issue this week. I uninstalled the program and also deleted the client folder under C:\Users\<user>\AppData\Local\GalaxyBudsClient, before reinstalling the latest version. Program launched fine. Try deleting the folder located in AppData before uninstalling/reinstalling and let us know if that helps!

**Comment by teonasnetto** [comment]
> I experienced this issue this week. I uninstalled the program and also deleted the client folder under C:\Users<user>\AppData\Local\GalaxyBudsClient, before reinstalling the latest version. Program launched fine. Try deleting the folder located in AppData before uninstalling/reinstalling and let us know if that helps!

This solved my problem

**Comment by ThePBone** [comment]
Looks like the config file got corrupted. This should no longer happen with the recent update.
