### ISSUE TITLE
[REQ] Workaround for Touchpad Lock not sticking

### ISSUE THREAD

**Issue by obrobrio2000** [ThePBone/GalaxyBudsClient#332]
**Is your feature request related to a problem? Please describe.**
"Lock touchpad" ("Block touches") feature doesn't stick after connecting buds to Windows. It always happens (100% of times) after (re)connecting the Buds (in my case Buds Pro). "Lock touchpad" is shown as enabled but the touches (and relative actions) still get recognized. Every time I (re)connect them to Windows I have to open the app and toggle off and on the Lock touchpad option.

**Describe the solution you'd like**
Can you add a (optional) workaround option that re-applies (= turns off and on again) the Lock touchpad option after (re)connecting the Buds to PC? Thanks in advance.

**Describe alternatives you've considered**
Manually turning off and on Lock touchpad option.

**Additional context**
It doesn't happen only with the unofficial app (this one) but also with the official Buds app in the Microsoft Store.

**Comment by obrobrio2000** [comment]
I think the automated issue assignment failed because I included two prefixes in the title :( Hope it gets noticed anyway!

**Comment by ThePBone** [comment]
I'm pretty sure one of the recent releases fixed issues with the touchpad lock. However, if it happens with the official app, too, it might have been a firmware bug.
