### ISSUE TITLE
[CRSH] The client dumps core when running from galaxybudsclient.desktop 

### ISSUE THREAD

**Issue by Linuxghost** [ThePBone/GalaxyBudsClient#334]
The client dumps core when running from galaxybudsclient.desktop;
Coredump:
https://pastebin.com/RPBpjpei
Tracedump
https://pastebin.com/8Ev5vD0B
Has something to do with
_galaxybudsclient.desktop[37307]: [12:14:44 WRN] Startup: Culture en-US unavailable. Falling back to C. System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
_
When starting from the terminal there is no problem at all.

**Comment by Linuxghost** [comment]
Changing DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0 in /usr/share/applications/galaxybudsclient.desktop resolved the issue.

**Comment by varad-kadam** [comment]
Same problem for me using v4.5.1.0 from the AUR.
Unfortunately, changing the DOTNET value doesn't fix it for me.

I can launch the app though the `cli` just fine though, just the app icon causing an issue.

**Comment by UnPossible-Me** [comment]
Same problem here.
Using v4.5.1.0 from the AUR.

Unfortunately, changing the DOTNET value to 0 doesn't resolve the issue for me.

**Comment by ByteDrummer** [comment]
I also installed using the AUR. This fixed it for me. I just needed to restart my computer.

**Comment by Christian-Klempau** [comment]
Doesn't work, with the variable set to 1 or to 0 :(
