### ISSUE TITLE
[BUG] How do I  launch manager on boot when Windows startup and minimize to tray

### ISSUE THREAD

**Issue by kamoniki** [ThePBone/GalaxyBudsClient#336]
I install v4.5.2 manager client in Windows 11 Pro 21H2 22000.708, but I cant find the setting about launch on boot when Windows startup and minimize to tray.

Any setting or installing I need to do? Thanks a lot.

![This is an image](https://i.imgur.com/GHintNm.jpg)

![This is an image](https://i.imgur.com/BGOz3fi.jpg)

**Comment by ThePBone** [comment]
This issue has already been fixed, but I haven't released a stable update yet.

You can download an updated version here: https://github.com/ThePBone/GalaxyBudsClient/actions/runs/2366081081

Related to #328
