### ISSUE TITLE
[REQ] Add option to start minimized to tray

### ISSUE THREAD

**Issue by soruh** [ThePBone/GalaxyBudsClient#342]
**Is your feature request related to a problem? Please describe.**
I have my DE automatically start the client on login but need to manually minimize it to the tray.

**Describe the solution you'd like**
I would like a command like flag or an option in the settings that starts the application minimized to the tray.

**Comment by ThePBone** [comment]
You can use this command-line switch:
```
galaxybudsclient /StartMinimized
```
See #341

**Comment by soruh** [comment]
Ah thank you, sorry for the spam. I tried `galaxyclient --help` which did not print anything and just started the client. So I assumed there were no flags and only looked through the open issues. Maybe adding a help message for command line flags would be a good idea.
