### ISSUE TITLE
[BUG] Buds pro在更新到AVF1版本后貌似无法与Galaxy Buds Manager链接

### ISSUE THREAD

**Issue by pxxcjp** [ThePBone/GalaxyBudsClient#345]
Buds pro在更新到AVF1版本后貌似无法与Galaxy Buds Manager链接

把buds pro更新到最新版本，然后尝试连接Buds pro在更新到AVF1版本后貌似无法与Galaxy Buds Manager链接，应该无法直接连接，

Windows 10专业版 19042.1706 64位 中文
![IMG_20220713_224202_075](https://user-images.githubusercontent.com/74781794/178762936-aab3fb29-edd9-4d31-9da2-7877879943bc.jpg)
[application.log](https://github.com/ThePBone/GalaxyBudsClient/files/9103307/application.log)
[Uploading application.log…]()
![Uploading IMG_20220713_224202_075.jpg…]()
![IMG_20220713_224203_818](https://user-images.githubusercontent.com/74781794/178762944-acc0e88a-0f84-4063-9bef-5658fb7c8c50.jpg)
![IMG_20220713_224207_892](https://user-images.githubusercontent.com/74781794/178762949-6bcbf67a-5154-4774-a1b0-88ccb9dc040b.jpg)
![IMG_20220713_224210_131](https://user-images.githubusercontent.com/74781794/178762955-c1ce38cf-cbda-4538-971d-c4f923931e43.jpg)

**Comment by pxxcjp** [comment]
如果直接链接，会一直加载，但是连接电脑时耳机大部分功能是正常的

**Comment by pxxcjp** [comment]
我也尝试过清除电脑和耳机的连接，清除Galaxy Buds Manager数据，但是，并没有用

**Comment by pxxcjp** [comment]
我尝试使用我的旧电脑，我的耳机之前可以在我的旧电脑上正常连接manager，工作的很好，但是今天我尝试后发现不行。

**Comment by pxxcjp** [comment]
![image](https://user-images.githubusercontent.com/74781794/178859399-408979c3-9f55-4483-a1e4-04b5b68099e7.png)

**Comment by pxxcjp** [comment]
> 
官方应用可以正常连接，但是我使用manager无法正常连接，我没有尝试使用两个应用同时连接我的buds

**Comment by pxxcjp** [comment]
但是4.4.1版本的manager可以正常工作，，，，，，4.5.2版本不行

**Comment by joosly** [comment]
,,我也是，而且那个版本也不能用

**Comment by YexuanXiao** [comment]
> 我好像知道原因了，之前我的耳机是buds＋然后换了budspro连不上，只要右上角的选项中重新注册设备就行了

问题解决了的话就自己close吧
