### ISSUE TITLE
[BUG] For buds2 the noise cycle switching mode & old version firmware& proximity measurement

### ISSUE THREAD

**Issue by yangyhua** [ThePBone/GalaxyBudsClient#348]
**Describe the bug**  
1. the noise cycle switching mode not work, actually is ANC->Ambient.
2. cant search old version firmware.
![image](https://user-images.githubusercontent.com/29419816/181291538-5f84b41f-93e0-413b-9a4c-31430dc99478.png)
3. proximity measurement L&R both display fail but 
![image](https://user-images.githubusercontent.com/29419816/181291918-691b7062-dc3f-4ead-bb9d-49572ebbb3d4.png)
![image](https://user-images.githubusercontent.com/29419816/181291794-c4672918-d5aa-469f-8d60-3ee90e4cb878.png)
![image](https://user-images.githubusercontent.com/29419816/181292899-9bc39353-0cac-4b6c-acf4-94f1ce1f7a0e.png)

**Desktop (please complete the following information):**  
 - OS: Windows 10 Pro 64bit OS Build number 19044.1826, default system language en-US 
 - Application version: 4.5.1.0

**Comment by ThePBone** [comment]
> the noise cycle switching mode not work, actually is ANC->Ambient.

This noise cycle switching mode was a hidden option that I found on the Buds Pro. It looks like they never added this to the Buds2, so I can't do anything about it except hiding the option.

> cant search old version firmware.

Maybe the server was down for a moment, but it works now for me. If the list is still empty, then a firewall might block access to my [firmware server backup](https://fw.timschneeberger.me/v2/firmware). 

> proximity measurement L&R both display fail

This is normal if you are wearing the earbuds in your ears, if they are in the case, or if the proximity sensor is blocked by another object.

**Comment by binning42** [comment]
> > the noise cycle switching mode does not work, actually is ANC->Ambient.

>This noise cycle switching mode was a hidden option that I found on the Buds Pro. It looks like they never added this to the Buds2, so I can't do anything about it except hide the option.

It's quite strange. When I first use bud2 it connects with BudsClient on PC not galaxy wearable on Samsung device, the cycle mode is working. But after I connect galaxy wearable and update firmware, and then connect back to BudsClient, I find cycle mode does not work. Therefore, I think this is a bug.

**Comment by binning42** [comment]
>>cant search old version firmware.

> Maybe the server was down for a moment, but it works now for me. If the list is still empty, then a firewall might block access to my [firmware server backup](https://fw.timschneeberger.me/v2/firmware).

I can access this URL in explorer. log is below 
![image](https://user-images.githubusercontent.com/29419816/181518190-03d800e9-7237-4385-86aa-c5d6bb2ee19a.png)

**Comment by nift4** [comment]
@ThePBone this was addressed by #465 you can close it
