### ISSUE TITLE
[REQ] System tray icon on Linux

### ISSUE THREAD

**Issue by alba4k** [ThePBone/GalaxyBudsClient#354]
**Is your feature request related to a problem? Please describe.**
_No icon appears in the system tray to signal that the program is still running in background._

**Describe the solution you'd like**
_The white "wear" icon should have place in the system tray._

**Describe alternatives you've considered**
\-

**Additional context**
It apears on Windows

[what I'm referring to as system tray](https://i.imgur.com/jdiasS9.png)

**Comment by linesquarecube** [comment]
Would also love to see a tray information on linux while wearing my buds! As there is also a script available to check the battery status (https://github.com/ThePBone/GalaxyBuds-BatteryLevel), this information would be a great addition. As I'm using gnome, perhaps there is a possibility to implement this via an extension. 

Anyone out there with the ability to implement something like this :smiley:? Unfortunately I'm not a programming guy :sob:

**Comment by ThePBone** [comment]
This is already implemented, but I haven't published an update yet. However, you can grab a precompiled binary with tray support here: https://github.com/ThePBone/GalaxyBudsClient/actions/runs/3266325817 (scroll down)

**Comment by alba4k** [comment]
This sounds awesome, I'll check it out as soon as I get home this evening :)

Thanks again for all the work you put into this project!

**Comment by alba4k** [comment]
This sounds awesome, I'll check it out as soon as I get home this evening :)

Thanks again for all the work you put into this project!

**Comment by alba4k** [comment]
@ThePBone I'm not seeing a system tray icon, even when launching the binary you linked

![picture](https://user-images.githubusercontent.com/84153269/197038611-b42dfeb2-e2b4-46b9-b844-b6fecf902e9b.png)

**Comment by Eternex49** [comment]
After downloading the binary, I have the same problem as @alba4k

**Comment by alba4k** [comment]
Hey, @ThePBone , got any news? Never heard back from you, but again, the binary you linked doesn't have any system tray icon either

**Comment by alba4k** [comment]
Actually, the tray icon does appear in hyprland when using waybar (wayland). It doesn't in polybar when using i3wm (X11)

**Comment by alba4k** [comment]
I'll just close this since the issue is probably lying withing polybar

**Comment by Eternex49** [comment]
@alba4k The issue doesn't lie within polybar. I use dwm with the system-tray patch, so this should be reopened and systematically troubleshooted.
