### ISSUE TITLE
[BUG] Doesn't recognise Galaxy Buds2 if they have custom name

### ISSUE THREAD

**Issue by iliqiliev** [ThePBone/GalaxyBudsClient#359]
The app doesn't recognize the buds even though they are connected and work normal.

You can open the app on the phone, reset them and then they are recognized correctly and work even after renamed so it's not really a big problem.

Both on Windows 10 and Arch Linux
App version 4.5.2

**Comment by AbhayAysola** [comment]
Kinda unrelated, but is there anyway to change the name from this client?

**Comment by ThePBone** [comment]
> Kinda unrelated, but is there anyway to change the name from this client?

No, at least not yet. I can look into adding it, but I don't have a device that supports personalized names for testing.

**Comment by AbhayAysola** [comment]
Ah no problem, thanks for your work on this wonderful client though.
