### ISSUE TITLE
[Windows] Does not minimize to the tray [BUG] 

### ISSUE THREAD

**Issue by vmarque** [ThePBone/GalaxyBudsClient#360]
**Describe the bug**  
Minimize to tray option is missing in the settings menu after version 4.4.0.0, without this option when closing the application the use of the pop up is no good and it is necessary to always keep the application window open in the taskbar, which can cause annoyance.

**To Reproduce**  
Minimize to tray option not available in settings menu

**Expected behavior**  
Bring back the option to minimize to tray instead of closing the application

**Screenshots**  
![Captura de tela 2022-08-31 125907](https://user-images.githubusercontent.com/88336901/187724599-c5210971-f6ca-45e8-ad9a-8f28c21dc620.jpg)

**Desktop (please complete the following information):**  
 - OS: Windows 11 (21H2)
 
 - Application version: 4.51.1.0

**Additional context**  

**Log files**  
In most cases if you have a bug, log file will be required - it is located at ```%localappdata%\GalaxyBudsClient\application.log```

**Comment by feumpi** [comment]
i had the same issue, and having the app always shown on taskbar is quite anoying. as a temporary workaround, [Traymond](https://github.com/fcFn/traymond) can be used to forcefully minimize (most apps) to tray.

**Comment by Swordfishx86** [comment]
You can set `MainWindow.Instance.OverrideMinimizeTray` to false in line 73 of `GalaxyBudsClient\App.xaml.cs`. Doing so will cause GalaxyBudsClient to minimize to tray when you click the close-button.

**Comment by Swordfishx86** [comment]
https://github.com/ThePBone/GalaxyBudsClient/blob/master/GalaxyBudsClient/App.xaml.cs
But you have to compile the application yourself.

**Comment by maxlmuller** [comment]
This was fixed on #328 but the updated binaries of the solution are expired.
@ThePBone Is there another way to download the fixed version?

**Comment by vmarque** [comment]
I forked myself and made the parameter change as explained by @Swordfishx86 , but I don't know how to compile the application :(

**Comment by ThePBone** [comment]
Here are updated binaries: https://github.com/ThePBone/GalaxyBudsClient/actions/runs/3401616712

**Comment by lanpff** [comment]
The updated binaries of the solution are expired.
@ThePBone Is there another way to download the fixed version,please?

**Comment by lanpff** [comment]
> 以下是更新的二进制文件： https://github.com/ThePBone/GalaxyBudsClient/actions/runs/3401616712

 The updated binaries of the solution are expired.Is there another way to download the fixed version,please?

**Comment by ThePBone** [comment]
There is a new release (v4.5.3-beta) available now, check the release section.

**Comment by lanpff** [comment]
> 现在有一个新版本（v4.5.3-beta），请查看发布部分。

It is woking again, thank you ~ (*^▽^*)
