### ISSUE TITLE
[REQ] Support for Galaxy Buds2 Pro

### ISSUE THREAD

**Issue by tetsugo** [ThePBone/GalaxyBudsClient#362]
**Is your feature request related to a problem? Please describe.**
App doesn't support Galaxy Buds2 Pro, the new model for the Buds lineup:
https://www.samsung.com/us/mobile-audio/galaxy-buds2-pro/

**Describe the solution you'd like**
App should support this Buds since the official app doesn't recognizes it on Windows 11

**Describe alternatives you've considered**

**Additional context**

**Comment by ThePBone** [comment]
I have added untested support for them. However, I can't test it because I don't own the earbuds.
It's possible that it won't work right out of the box, but you can try it out.

You can download a precompiled beta build on these pages:

Windows: [ThePBone/GalaxyBudsClient/actions/runs/2949009351](https://github.com/ThePBone/GalaxyBudsClient/actions/runs/2949009351)
Linux: [ThePBone/GalaxyBudsClient/actions/runs/2949009328](https://github.com/ThePBone/GalaxyBudsClient/actions/runs/2949009328)

**Comment by ZeRoX93** [comment]
It works with this build [GalaxyBudsClient_Setup_64bit_4.5.2-f8e121.exe], but what I'm missing is the option to enable and disable Voice Detect, 360 Audio :) Keep up the good work. 👍 

If you need some testing, don't hesitate to contact me 👍

**Comment by acidtoyman** [comment]
It does work nicely out-of-the-box!

A missing feature is the Earbud Fit Test.  I don't know if this is maybe a Wearbles app-only feature or something, but it would be Nice to Have™.

**Comment by retromack** [comment]
Is there a way to downgrade to `R510XXU0AVG5` from the current `R510XXU0AVI7` <https://doc.samsungmobile.com/SM-R510/XAR/doc.html>

**Comment by ThePBone** [comment]
No, I don't have currently any firmware files for the Buds 2 Pro backed up.

**Comment by retromack** [comment]
Okay, Let me keep looking for the files i post it here if I find the firmware files for `R510XXU0AVG5 `

**Comment by retromack** [comment]
> Okay, Let me keep looking for the files i post it here if I find the firmware files for `R510XXU0AVG5 ` 

Quick update on this. 
Sadly I couldn't find it snywhere after a day worth of searching the internet.

**Comment by Jacob-Darka** [comment]
> It works with this build [GalaxyBudsClient_Setup_64bit_4.5.2-f8e121.exe], but what I'm missing is the option to enable and disable Voice Detect, 360 Audio :) Keep up the good work. 👍
> 
> If you need some testing, don't hesitate to contact me 👍

does the app support Voice Detect now, or not yet?

**Comment by PashaKagan** [comment]
Hey,
As an owner of buds pro 2, is there a way for me to find the said firmware? I'll contribute it if I knew how to extract.

**Comment by GGProGaming** [comment]
voice detect on this would be great. Awesome app though! Another bug I found was the option to cycle between ANC, Ambient, and Off didn't work and only did ANC and ambient. Overall great job!

**Comment by Dmattiazzi** [comment]
Hi, I have the same problem, bud the beta files don't exist.
Please rebuild, thanks

**Comment by Dmattiazzi** [comment]
> Hi, I have the same problem, bud the beta files don't exist. Please rebuild, thanks

Hi found e download the last buids, but don't connect width the Galaxy Buds2 Pro..

**Comment by Zoneykid** [comment]
Using 4.5.2, connects just fine with my buds2 pro. Missing some of the features from the app but works well enough for me to use daily.
@Dmattiazzi Are you having issues getting the buds to pair with your computer or to connect to the client?

**Comment by Dmattiazzi** [comment]
On the computer with windows 10 or 11, they connect to windows but not the manager.
Where do I find night builds?

**Comment by GGProGaming** [comment]
Could we get a time frame when the rest of the features will come to this client? Wonderful work though!

**Comment by LoreleiPenn** [comment]
Hello.

I cannot download the beta for manual selection of the buds2 pro and thus cannot use the client while my buds2 pro are connected to the system and the sound works.

I am running Arch Linux with kernel 6.1.11-zen1-1-zen.

Thank you.

**Comment by ThePBone** [comment]
I forgot to update the link for the Linux binaries above. Here's the correct link:
https://github.com/ThePBone/GalaxyBudsClient/actions/runs/3781420127

**Comment by LoreleiPenn** [comment]
Thank you very much!!

This work pretty nice for me!!

**Comment by 5ham5h33r** [comment]
It works perfectly except the lock touchpads toggle seems reversed? Touchpad works when I have it ticked and doesn't when unticked

**Comment by aleksei-saharov** [comment]
Hi

Works food to me. However, does anyone found firmwares?
I have found only the first and the second version sources on Samsung Open Source portal. Of course, it's not possible to use sources as is((

In my case, Buds2Pro are disconnecting on a call start with the latest firmware. That's why I want to downgrade it.

**Comment by neoaraxis** [comment]
Does not work for me. I am on Firmware version: R510XXU0AWA

**Comment by neoaraxis** [comment]
> Works for me, but initial connecting/pairing them was a pain - didn't work via gnome bluetooth settings or via blueman. Worked via command line:
> 
>     1. Open terminal and type `bluetoothctl`,
> 
>     2. In it's prompt type `scan on`
> 
>     3. Put your earbuds into pairing mode (put them in the case, close the case for 6 seconds, open the case and don't take earbuds out)
> 
>     4. Find the address of your buds (bluetooth addresses look like XX:XX:XX:XX:XX:XX). You should be able to see it in the scan logs. Alternatively, if you have blueman installed, you can look it up in it's list of devices.
> 
>     5. type `pair XX:XX:XX:XX:XX:XX` (just use your address) and see how it goes through pairing (it's usually a few seconds)
> 
>     6. type `scan off`
> 
>     7. type `exit` to close bluetoothctl and get back into your normal shell

This method works. And without using the application.

**Comment by schdie** [comment]
Are the links expired?

**Comment by rahulroy9202** [comment]
Does the seamless connect work for Buds 2 Pro?

**Comment by MPW1412** [comment]
Thanks for all the work!

I have issues setting the action button to toggle or cycle ANC modes when long pressing. Does that work for you?
