### ISSUE TITLE
[REQ] Option to start minimized to tray

### ISSUE THREAD

**Issue by feumpi** [ThePBone/GalaxyBudsClient#363]
**Is your feature request related to a problem? Please describe.**
I always block my buds touchpad because i end up pausing the current media while ajusting them on my ears. To keep the touchpad blocked, the app needs to be always open, so I add it autostart. But there's no need to present the app window everytime I log in, as I only want it running in the background.

**Describe the solution you'd like**
I would like an option for the app to start already minimized to tray, without presenting it's window on startup.

**Describe alternatives you've considered**
The app runs on startup and I manually close the window (minimizing to tray) every time I log in.

**Additional context**
As an example, Discord has this feature as both a GUI toggable option and a `--start-minimized` command line argument.

![Discord start minimized option](https://techswift.org/wp-content/uploads/2021/07/Discord-Toggle-Icon-Next-to-Open-Discord-in-Windows-Settings.jpg)

**Comment by Swordfishx86** [comment]
You can use the argument  /StartMinimized to start the Galaxy Buds Client minimized to tray.

**Comment by tristangrimaux** [comment]
I was about to ask the same thing, this option is not documented!
