### ISSUE TITLE
[BUG] FirmwareRemoteClient: 0 firmware found, galaxy buds 2 pro

### ISSUE THREAD

**Issue by 24fpsDaVinci** [ThePBone/GalaxyBudsClient#375]
**Describe the bug**  
is this an error or does this mean no new firmwares are available? the buds have not been updated before

**To Reproduce**  
update firmware

**Expected behavior**  
update

**Desktop (please complete the following information):**  
fedora 37, latest GB client

**Comment by ThePBone** [comment]
Buds 2 Pro firmware is now being collected from version `R510XXU0AVK3` onwards.
You also need to get an updated version due to a bug from here otherwise the firmware list won't show anything:  https://github.com/ThePBone/GalaxyBudsClient/issues/361#issuecomment-1350193720
