### ISSUE TITLE
[BUG]  - Unable to establish connection

### ISSUE THREAD

**Issue by michailspiridonov** [ThePBone/GalaxyBudsClient#377]
**Describe the bug**  
After reconnecting Galaxy Buds 2, the app give the error: 
![image](https://user-images.githubusercontent.com/32950948/207574806-56b8aabb-5452-4933-a29f-99c78a0bcc38.png)
After unregistering my buds (while still being connected) the same error appears

**Rebooting fixes the problem**
**To Reproduce**  
1.  Launch the buds manager
2. Connect the buds
3. Disconnect the buds from the pc (I usually also lock - S3 sleep)
4. Connect the buds again
5. Observe the error

**Expected behavior**  
After connecting by buds again in the same session, the buds manager accepts them

**Screenshots**  
Screenshots in the description

**Desktop (please complete the following information):**  

 - Application version: 
OS:            Arch Linux x86_64
Kernel:     6.0.12-arch1-1
DE:            Plasma 5.26.4
CPU:         Intel i7-7700HQ (8) @ 3.800GHz
**Additional context**  
As I said, rebooting my PC fixes the problem, and it usually occurs when I leave the PC for a while, lock it -> it goes into sleep. When I come back, I am unable to use the buds manager, but the buds themselves work fine.

**Log files**  
[application.log](https://github.com/ThePBone/GalaxyBudsClient/files/10227036/application.log)

**Comment by ThePBone** [comment]
This should be fixed with the current version
