### ISSUE TITLE
Budsprohave new firmware in September？

### ISSUE THREAD

**Issue by stfizer** [ThePBone/GalaxyBudsClient#379]
It seems that there is an update of new firmware in Budpro in September 2022. I heard about it in other forums. I don't know if anyone has pushed this firmware update, such as avg1 or avg5.

**Comment by ThePBone** [comment]
According to Samsung's official firmware changelog for the Buds Pro, there was no firmware update released in September: https://doc.samsungmobile.com/sm-r190/xar/doc.html

The latest firmware is `R190XXU0AVF1` which was rolled out in June/July. Maybe you are confusing the Buds Pro with the Buds Pro 2.

**Comment by stfizer** [comment]
OK thank you

**Comment by stfizer** [comment]
> According to Samsung's official firmware changelog for the Buds Pro, there was no firmware update released in September: https://doc.samsungmobile.com/sm-r190/xar/doc.html
> 
> The latest firmware is `R190XXU0AVF1` which was rolled out in June/July. Maybe you are confusing the Buds Pro with the Buds Pro 2.

OK，thank you
