### ISSUE TITLE
[BUG] Mic not working with buds 2 and RHEL9

### ISSUE THREAD

**Issue by NicTanghe** [ThePBone/GalaxyBudsClient#384]
**Describe the bug**  

Mic not working with buds 2 and RHEL9

**To Reproduce**  

Try to set the mic as bneing used in dota 2 or browser on rhel9.

**Expected behavior**  
mic works

**Screenshots**  

**Desktop (please complete the following information):**  
 - OS: RHEL 9
 - Application version: 4.5.1.0

**Additional context**  

**Log files**  
given location  does not exist in linux.
```%localappdata%\GalaxyBudsClient\application.log```

**Comment by alba4k** [comment]
This is not related to the app

most bluetooth earphones only show a mic when being used as a phone headset.

Install something like pavucontrol, go to a device configuration menu and change the device mode to headset

the mic should now show up and work
