### ISSUE TITLE
[BUG] failed to upload firmware battery low

### ISSUE THREAD

**Issue by ahmedtsadek** [ThePBone/GalaxyBudsClient#385]
**Describe the bug**  
I have a SM-R180 and trying to install firmware as I got a replacement bud with low firmware both buds and the case are charged over 50% and still getting error battery low 15%

screenshot
https://www.linkpicture.com/q/Capture_163.png

**Comment by volarye** [comment]
**to fix this:**
1. find FirmwareTransferManager.cs
2. you need to comment this:
` /*
 if (DeviceMessageCache.Instance.ExtendedStatusUpdate?.IsCoupled ?? true)
            {
                if ((DeviceMessageCache.Instance.BasicStatusUpdate?.BatteryL ?? 0) < 15 ||
                    (DeviceMessageCache.Instance.BasicStatusUpdate?.BatteryL ?? 0) < 15)
                {
                    Error?.Invoke(this, new FirmwareTransferException(FirmwareTransferException.ErrorCodes.BatteryLow,
                        Loc.Resolve("fw_fail_lowbattery")));
                    return;
                }
            }
            else if ((DeviceMessageCache.Instance.BasicStatusUpdate?.BatteryL ?? 0) < 15 &&
                     (DeviceMessageCache.Instance.BasicStatusUpdate?.BatteryL ?? 0) < 15)
            {
                Error?.Invoke(this, new FirmwareTransferException(FirmwareTransferException.ErrorCodes.BatteryLow,
                    Loc.Resolve("fw_fail_lowbattery")));
                return;
            }
*/ `
3. rebuild app and all will be fine )))

**Comment by ThePBone** [comment]
Fixed by https://github.com/ThePBone/GalaxyBudsClient/commit/6cb5a1ce3434e1686efbcbba427b3ad1ee4fb371
