### ISSUE TITLE
[BUG] Buds2 - Various issues

### ISSUE THREAD

**Issue by 132ikl** [ThePBone/GalaxyBudsClient#386]
**Describe the bug**  
Hi, just wanted to report in with what doesn't work on my Buds2.

- Voltage readout is 0.00V for both buds
- Ambient sound levels higher than Normal don't work (all tone options work however)
- Similar firmware version as #348 (mine reports version `R???XXU0AVK5`)
- Build Info and Battery Type both report "Waiting for response..."

**To Reproduce**  
N/A

**Expected behavior**  
N/A

**Screenshots**  
N/A

**Desktop (please complete the following information):**  
 - OS: Arch Linux, kernel version 6.1.9-arch1-1, x86_64, LANG=en_US.UTF-8
 - Application version: `4.5.2-4` from AUR

**Additional context**  
Let me know if you need me to test anything else for the Buds2 or need any more information!

**Log files**  
I looked through the log file but there wasn't any information relevant to the above issues.

**Comment by nift4** [comment]
To add to that, "Touchpad lock" seems to be inverted for me on R177XXU0AWB1

**Comment by nift4** [comment]
@ThePBone all of these have been fixed by #442 and #465, you can close it
