### ISSUE TITLE
Application interfere with connection (Buds2)

### ISSUE THREAD

**Issue by thelegendaryjohn** [ThePBone/GalaxyBudsClient#389]
Every time I run the app, the audio will be stuttered, and can be solved every time by quitting the app, so I'm pretty sure it's the culprit

**Comment by gamesfrager** [comment]
Same here. Running the latest release 4.5.2 on Windowqs 10 64bit with Galaxy buds pro 2.

**Comment by ThePBone** [comment]
This sounds like it's an issue with the Bluetooth adapter on your computers. It might not be capable of opening multiple simultaneous connections to the same device (1x audio connection, 1x serial connection for the app)
