### ISSUE TITLE
No Chinese translation was found

### ISSUE THREAD

**Issue by captainwayland** [ThePBone/GalaxyBudsClient#39]
No Chinese translation was found

**Comment by ThePBone** [comment]
afb3363aede25af7c580592ef279d1a4252097a9 fixes this issue.

Here is an updated installer without this issue: [Setup_GalaxyBudsManager_2.3.3.1.zip](https://github.com/ThePBone/GalaxyBudsClient/files/5341783/Setup_GalaxyBudsManager_2.3.3.1.zip)
