### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by danny9090** [ThePBone/GalaxyBudsClient#399]
Hello today i connected my Galaxy Buds 2 Pro with my PC and Downgraded the Firmware to the first on the List after that i cant connect my Galaxy Buds 2 Pro anymore can anyone please Help me :(

**Comment by ThePBone** [comment]
Downgrading can lead to unexpected behavior. Returning them or sending them to a repair centre is the only option in case of a hard brick.
