### ISSUE TITLE
virustotal results 5 detections

### ISSUE THREAD

**Issue by al3xander** [ThePBone/GalaxyBudsClient#4]
checking installer with virustotal.com it says
5 engines detected this file

like BehavesLike.Win32.AdwareAdload.dc

see also
https://www.virustotal.com/gui/file/20d942b33e52e6141732d8c137121904945acf2480c505b207f14eb63b910d49/detection

is there any information about it?

**Comment by ThePBone** [comment]
No, I don't have any idea why that could happen. I'm not registering the app in the autostart, nor does it mess with system files. Also, the McAfee GW edition scanner detects malware while the normal McAfee scanner doesn't for some reason.
I'll look into this issue later, maybe there's something I can do about it. 

You can also build the app directly from sources if you don't feel save using the installer

**Comment by ThePBone** [comment]
I did some research and this seems to be a common issue with unsigned installers. (The actual executable of the Manager has zero virus detections)
The installer framework I'm using (NSIS, nullsoft scriptable install system) [has a wiki page about these false positives (not updated anymore)](https://nsis.sourceforge.io/NSIS_False_Positives).

I'll try to sign the installer executable with an Authenticode signature in the future. This will also display a nicer and more user-friendly UAC dialog in Windows.
