### ISSUE TITLE
[BUG] My Samsung Buds Pro can‘t find the downgraded firmware

### ISSUE THREAD

**Issue by kai710** [ThePBone/GalaxyBudsClient#401]
[BUG] My Samsung Buds Pro can‘t find the downgraded firmware.
![503](https://user-images.githubusercontent.com/74440809/230890351-5467da4b-de37-443a-b0ae-ed133e9586cc.png)

**Comment by Downey131** [comment]
I have the same issue.

**Comment by ThePBone** [comment]
I disabled my firmware server because one guy with Buds 2 Pro bricked his earbuds while downgrading.

I've re-enabled the server for all models except the Buds2 and Buds2 Pro for safety reasons.

Downgrading is dangerous and can brick your devices.
