### ISSUE TITLE
[REQ] Global hotkey for battery charge popup

### ISSUE THREAD

**Issue by StegBrind** [ThePBone/GalaxyBudsClient#402]
**Is your feature request related to a problem? Please describe.**
Every time I want to check my earbuds' battery charge, I always have to press Alt+Tab on Windows or WinKey on Gnome Linux to actually check it (see the window).

**Describe the solution you'd like**
I guess it'd be way more convenient to have a configurable global hotkey to trigger the battery charge popup window and be able to easily check the information about your battery. We just need a cross-platform way to capture pressed and released keys globally. There is a great library called ["libuiohook"](https://github.com/TolikPylypchuk/libuiohook/tree/56e8cb88cbe9a337e6ad8b1e4e12e40e96fe02f4) written in C and with a [C# wrapper](https://github.com/TolikPylypchuk/SharpHook) for it. I can implement it myself and make a PR if you are positive on my feature request.

**Describe alternatives you've considered**
We need to make an implementation for the global hotkey handler. Do you think we'd better to extend the IHotkeyReceiver interface, or just create a separate one just for this small feature?

**Additional context**
Thank you for your efforts, really useful application!

**Comment by ThePBone** [comment]
This has been possible on Windows for some time, but the latest release also adds global hotkey support for Linux/X11 and macOS.

It can be found under 'Advanced settings'.
