### ISSUE TITLE
Buds Pro 2 - no voltage displayed

### ISSUE THREAD

**Issue by AndKe** [ThePBone/GalaxyBudsClient#410]
**Describe the bug**  
please observe the missing voltage.
![image](https://github.com/ThePBone/GalaxyBudsClient/assets/1468842/df164fd0-7bde-4b5b-b14d-a14ebb44af28)

**To Reproduce**  
Connect Buds Pro 2

**Desktop (please complete the following information):**  
Ubuntu 23.04
 - Application version: 
4.5.2 release

Additional information:
I would like to see the voltage to check if they make them fail after a few years by design, Li-ion batteries are not a fan of a high state of charge over time.

It would be a fantastic feature if the app could set the maximum charge level. 
When receiving new buds, they are limited to 60% SOC - but seem to charge to 100% every time since. if that is at 4.2v , then it's quite bad for life expectancy.

**Comment by ThePBone** [comment]
The newer Buds models don't seem to report voltages anymore. 
The next update will hide the voltage text fields from the UI for these models.

Setting the maximum charge level is unfortunately not possible because there's no support in the firmware for that.
