### ISSUE TITLE
[REQ] Update icon to match the Windows Galaxy Buds app

### ISSUE THREAD

**Issue by sidevesh** [ThePBone/GalaxyBudsClient#411]
Can you replace the icon with https://aur.archlinux.org/cgit/aur.git/plain/icon_white.png?h=galaxybudsclient-bin ?
This is the icon of the Windows Galaxy Buds app https://apps.microsoft.com/store/detail/galaxy-buds/9NHTLWTKFZNB?hl=en-in&gl=in.

I have already mentioned this in a comment to the arch aur package in case its more relevant there but thought I will share it here too just in case.

**Comment by sidevesh** [comment]
fyi, the arch package has gotten the icon updated already, that does it for me but might be good to use an updated icon for upstream and other downstream distros too

**Comment by blackd** [comment]
Using assets from Samsung is probably a copyright infringement.
I don't think it's a good idea unless you have permissions.
