### ISSUE TITLE
[REQ] Opening GUI after clicking the tray icon

### ISSUE THREAD

**Issue by yigitcanustek** [ThePBone/GalaxyBudsClient#412]
**Describe the solution you'd like**
Most things works fine. But when I minimize the program, I can't maximized it again. I mean, can't reach the GUI. To able to solve that, I have to start from executable file(.bin file)

**Describe alternatives you've considered**
I think double click to system tray icon solve that issue. Right click show the details, info etc.

Thanks :)

**Comment by ThePBone** [comment]
This is already the normal behaviour and works on most desktop environments. It is probably an issue with the UI toolkit or the DE. 
Either way, I've added an 'open' menu item as a workaround. The UI toolkit currently uses a legacy API to register tray icons; once they upgrade, these issues will probably be resolved.
