### ISSUE TITLE
cant connect buds pro[BUG] 

### ISSUE THREAD

**Issue by mayavoid** [ThePBone/GalaxyBudsClient#421]
**Describe the bug** 
it connects to  pc, plays music as normal but fails to connect to app, I have similar problem on android, it just won't connect to app and I cant access the best features, its impossible its fake as it was provided by official phone carrier as bundle with phone

**To Reproduce**  
idk try to connect?

**Expected behavior**  
work

**Screenshots**  
![image](https://github.com/ThePBone/GalaxyBudsClient/assets/115767286/08322cb5-1a5b-4fe6-bc56-bb40a2b8776a)

**Desktop (please complete the following information):**  
 - OS: Windows 10  [64bit] OS Build number, default system language 
![image](https://github.com/ThePBone/GalaxyBudsClient/assets/115767286/96c1ad41-260b-40ef-9efa-829239501732)
 - Application version: 

**Additional context**  
not connecting on phone to app too, but otherwise works plays music, on previous phone, the one it was in bundle with, and another one, it connected to app, on both, mine phone is also samsung so idk what's the issue

**Log files**  
In most cases if you have a bug, log file will be required - it is located at ```%localappdata%\GalaxyBudsClient\application.log```
[application.log](https://github.com/ThePBone/GalaxyBudsClient/files/12428456/application.log)

**Comment by ThePBone** [comment]
The error and the fact that the official app isn't working either indicates that they are either fake or have a firmware issue. I can't help with that, unfortunately.
