### ISSUE TITLE
Cannot find old firmware R510XXU0AVK3

### ISSUE THREAD

**Issue by nick-gregory** [ThePBone/GalaxyBudsClient#423]
I got GalaxyBudsClient up and running on Windows 10. No issues whatsoever.

However, I cannot find actual previous firmware to install.

I have found this website: https://budsfirm.onrender.com/ But at the moment it's not working.

Can anyone suggest link to R510XXU0AVK3 ?

Thank you!

**Comment by ThePBone** [comment]
You can find my full firmware archive here: https://github.com/ThePBone/galaxy-buds-firmware-archive
