### ISSUE TITLE
[BUG] Auto-reconnect doesn't work as expected

### ISSUE THREAD

**Issue by ProminentRetail** [ThePBone/GalaxyBudsClient#427]
**Describe the bug**  

Turning Bluetooth off and on system-wide causes Galaxy Buds Manager to automatically detect the reconnection as expected; however, when I disconnect and reconnect my Buds Pro, Galaxy Buds Manager stays on the "Unable to establish connection" page until I manually press "Connect".

**To Reproduce**  
1. Connect buds.
2. Disconnect buds.

**Expected behavior**  

Connection is automatically re-established.

**Desktop (please complete the following information):**  
 - OS: NixOS 23.11, English
 - Application version: built commit a06eff7713fde924466ae1a214571a2b6f0d1a42 from source

**Additional context**  

This problem also occurred when I was using Windows.

**Log files**  

[application.log](https://github.com/ThePBone/GalaxyBudsClient/files/13040869/application.log)

Thank you! I appreciate your work on this app.

**Comment by ThePBone** [comment]
This should have been fixed by https://github.com/ThePBone/GalaxyBudsClient/pull/405.
The current version contains that patch.
