### ISSUE TITLE
Different UI icons for Buds/Buds+/Buds Live

### ISSUE THREAD

**Issue by Luke25361** [ThePBone/GalaxyBudsClient#43]
I've just been using [version 3.0](https://github.com/ThePBone/GalaxyBudsClient/releases/tag/3.0.0.0) with my Buds Live and it's working great!
One thing I've noticed is that the UI icons all depict the original Buds. This doesn't affect the functionality of the app in the slightest so it's not really a big deal, and the Buds & Buds+ icons are so similar that Buds+ users likely won't notice this anyway.
I'm not sure where the current UI icons came from, but I have come across line art for the Buds+ & Buds Live that might be useful if this request is deemed worthwhile:

- [BudsPlusPage_Compare_Icon_BudsPlus_D.jpg](https://image-us.samsung.com/SamsungUS/home/mobile/galaxy-buds-compare/BudsPlusPage_Compare_Icon_BudsPlus_D.jpg) (from [Samsung Galaxy Buds - Bluetooth Wireless Earbuds | Samsung US](https://www.samsung.com/us/mobile/audio/galaxy-buds/))
- [galaxy-buds-live-air-duck.jpg](https://images.samsung.com/is/image/samsung/p5/uk/support/mobile-devices/how-to-use-galaxy-buds-live-best-in-audio-quality/galaxy-buds-live-air-duck.jpg) (from [How to use Galaxy Buds Live best in audio quality | Samsung Support UK](https://www.samsung.com/uk/support/mobile-devices/how-to-use-galaxy-buds-live-best-in-audio-quality/))

Huge thanks for the work you've put into this project! Lockdown has meant I'm now using my Buds Live with my PC the majority of the time, so it's really nice to now have the same level of control over them as I do with my phone 🙂

**Comment by ThePBone** [comment]
I'm usually pulling most icons from the official Wearable plugin app. I just looked through the Buds Live plugin APK and found this one:
![fit_good_left](https://user-images.githubusercontent.com/38386967/96629393-d55ed380-1313-11eb-99b6-c4d770dea49b.png)

Although the Beans are colored black and not transparent unlike the original Buds icons, it shouldn't be too hard to edit them.
I'll insert these into the layout tomorrow to see if they look good and match the theme.

**Comment by ThePBone** [comment]
I updated the icons: 

![](https://user-images.githubusercontent.com/38386967/96740392-195be200-13c1-11eb-827a-5043ba02bff5.png)

I'll probably release a new update later which includes these changes.

**Comment by ThePBone** [comment]
Version 3.1 adds this: https://github.com/ThePBone/GalaxyBudsClient/releases/tag/3.1.0.0

**Comment by Luke25361** [comment]
This is fantastic, thank you! 😁
There are also some unique icons for [Connect/Factory reset](https://i.imgur.com/kMrPMp1.jpg), [Find my Earbuds](https://i.imgur.com/OHgxFyM.jpg), & [Touchpad](https://i.imgur.com/xyPGBbJ.jpg), but as before they don't affect the app's functionality at all so it might not be worth it.

**Comment by ThePBone** [comment]
Oh, I overlooked those. I'll add them in later
