### ISSUE TITLE
[REQ] Support for Galaxy Buds FE and multi-device.

### ISSUE THREAD

**Issue by nathan60107** [ThePBone/GalaxyBudsClient#430]
**Is your feature request related to a problem? Please describe.**
I purchased the Galaxy Buds FE and attempted to connect them to the GalaxyBudsClient. However, I discovered that the GalaxyBudsClient doesn't support the FE model, and it also lacks multi-device support. I found a workaround by manually adding the FE to the GalaxyBudsClient by selecting a different model type.
![圖片](https://github.com/ThePBone/GalaxyBudsClient/assets/18046878/497994a2-cf46-4892-9849-0677c5799d72)

**Describe the solution you'd like**
Support Buds FE and multi-device.

**Describe alternatives you've considered**
None

**Additional context**
Nothing. Thanks for creating this app.

**Comment by gitpkmx** [comment]
I too would love to see the Galaxy Buds FE  support! <3

**Comment by FreeHK-Lunity** [comment]
same issue. would love to see support implemented

**Comment by blaine-t** [comment]
> Hello guys, yesterday I buy the Galaxy Buds FE (and because that I was replying later).
> 
> You guys can connect the "Galaxy Buds FE" as "Buds2" manually into connection page. ![image](https://private-user-images.githubusercontent.com/72317733/294142220-393fd8e5-d0df-4dda-b107-78f8d8853979.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NzM1MzUsIm5iZiI6MTcwNDU3MzIzNSwicGF0aCI6Ii83MjMxNzczMy8yOTQxNDIyMjAtMzkzZmQ4ZTUtZDBkZi00ZGRhLWIxMDctNzhmOGQ4ODUzOTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDIwMzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmN2I1NWQxYzU1MWY0MjNlNjg5Y2QyMTlhMTQwNTA4MDkyZDg3NzY1NGY5YmE4OTZjNjA5Mzg5NzlmMDhhYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4ROFEN_MGWnuw5GU0PhpAuiVd66qZ3OJk3tAd5EyBC4)
> 
> Is my first time testing, recently 5 minutes testing and without any problems ![image](https://private-user-images.githubusercontent.com/72317733/294142401-9af886fc-0be5-4e39-a783-865c94df9e2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NzM1MzUsIm5iZiI6MTcwNDU3MzIzNSwicGF0aCI6Ii83MjMxNzczMy8yOTQxNDI0MDEtOWFmODg2ZmMtMGJlNS00ZTM5LWE3ODMtODY1Yzk0ZGY5ZTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDIwMzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZTZiNTBiZDQ0ZjAxMzU0Mjk5NTVmZDE2Yzg2NTljMTI3ZGI2MGU5ODI4MDQ5MjJmNzU2MDA3NTUyZmQzOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gF1npA1auI41o3emdCH_RIl-DJWl7STnw7oDcAW73vE)

If you do this and change touchpad settings it breaks the touchpad. I can't fix my touchpad now as it is stuck in a broken state presumably until I can get an Android phone to fix it. Everything else works but beware not to change touchpad settings with this app til FE is properly implemented.

**Comment by crisap94** [comment]
Any update on this?

**Comment by ThePBone** [comment]
Buds FE support is available in the latest release: https://github.com/ThePBone/GalaxyBudsClient/releases (although mostly untested)

I haven't started working on multi-device support yet, but there's already another issue (#214) open about that, so I'll close this one.
