### ISSUE TITLE
[REQ][Galaxy Buds Pro 2] Mute Mic during call

### ISSUE THREAD

**Issue by MPW1412** [ThePBone/GalaxyBudsClient#432]
I've only recently discovered, that Samsung didn't think of a way to mute the mic(s) of the Galaxy Buds Pro 2 during a call. 

I wonder, if there's a possibility to implement this as a function for the touch pad and assign it to a long press event during HFP?

And if that's not possible, would it be possible to execute a command on the host to mute the mic in pulseaudio?

```bash
pactl set-source-mute @DEFAULT_SOURCE@ toggle
```

**Comment by ThePBone** [comment]
That would need to be implemented in the HFP driver. The app doesn't control that.

But yes, you can execute a command:
1. Create a script file with your command and make it executable
2. In the app, you can select the 'Custom action...' menu entry for the touchpad action
3. Then select 'Run external program' as the custom action and select your script
