### ISSUE TITLE
Font size options

### ISSUE THREAD

**Issue by GiorgosChr** [ThePBone/GalaxyBudsClient#436]
A font size selection will be very much appreciated since on 4k screens the font appears tiny and almost unreadable.

**Comment by ThePBone** [comment]
Duplicate of #311 

The underlying UI toolkit used for this app doesn't support HiDPI out of the box on Linux currently.

They provide a workaround by setting an environment variable with scale factors manually: https://github.com/AvaloniaUI/Avalonia/wiki/Configuring-X11-per-monitor-DPI
