### ISSUE TITLE
[REQ] Better name for the app

### ISSUE THREAD

**Issue by sidevesh** [ThePBone/GalaxyBudsClient#461]
With all the improvements rolling in lately and the new macOS build,
the current "GalaxyBudsClient" name of the app seems a bit off,
can this be changed to "Galaxy Buds" or "Galaxy Buds Manager" to match the app window.

I would prefer "Galaxy Buds" with the app name in titlebar also changed from "Galaxy Buds Manager' to just "Galaxy Buds".

This would match the app to its official counterpart on Windows but then that maybe something we want to avoid and, in that case, "Galaxy Buds Manager" would work.

**Comment by nift4** [comment]
If you are on macOS, the Galaxy Buds Manager should be in menu bar, however this had to be disabled due to an Avalonia bug: https://github.com/AvaloniaUI/Avalonia/issues/14577

**Comment by sidevesh** [comment]
I meant the icon in the LaunchPad on macOS,
its called GalaxyBudsClient,
we would need to rename the CFBundleName on Info.plist and the app bundle name during build

**Comment by sidevesh** [comment]
also @nift4 unrealted but running the latest commit on macOS shows up like this with double titlebars
![Screenshot 2024-02-11 at 3 24 13 PM](https://github.com/ThePBone/GalaxyBudsClient/assets/17254413/ec1ce201-14b3-4a4f-affa-5134557649b2)
Great job on the macOS port btw, can't tell you how long I have been waiting for it :)

**Comment by nift4** [comment]
I believe the double titlebar issue is due to this: https://github.com/ThePBone/GalaxyBudsClient/commit/ee3d298fe6703670af0e7c29d418e16b7b794fb7
I'll fix it and rename the bundle

**Comment by sidevesh** [comment]
I see the name is updated now and also the double titlebar bug is gone, thanks @nift4 !
