### ISSUE TITLE
[BUG] Device name in popup is mismatched with the device

### ISSUE THREAD

**Issue by sidevesh** [ThePBone/GalaxyBudsClient#463]
The device name in the popup seems to be composed of USERNAME's followed by the model name,
but the username it gets is the shortname used by user's dir and not the full name specified in User settings,
which looks odd,

I think we should just show the device's bluetooth name here since when Galaxy Buds are paired with a Samsung phone,
they rename themselves to 'User's Galaxy Buds' anyways as you can see in the screenshot.

![Screenshot 2024-02-11 at 4 06 06 PM](https://github.com/ThePBone/GalaxyBudsClient/assets/17254413/a7f58c53-7e76-44d0-911e-899a7d3d8899)

**Comment by sidevesh** [comment]
@ThePBone do lmk your thoughts on this, I can take a look at implementing this.

**Comment by sidevesh** [comment]
I did, I couldnt find the function in the `BluetoothImpl` that returns the device name, could you point me to it in case I missed it ?

**Comment by ThePBone** [comment]
Yep, you're right. It hasn't kept track of the real device name until now. 

I changed that in commit dd87a0bf567ed76275a6c9168a2b01c437d57983. I've only tested it on Linux so far, but it should work with the Bluetooth backends for the other platforms, too.
