### ISSUE TITLE
[REQ] flash buds firmware independently

### ISSUE THREAD

**Issue by rainbow-krash** [ThePBone/GalaxyBudsClient#472]
**Is your feature request related to a problem? Please describe.**
When firmwares are mismatched between the right and left buds the firmware update will always fail stating to "charge to at least 15%" (even if both buds are fully charged). This seems to be because mismatched buds will not connect at the same time, it will only connect to one bud or the other.

**Describe the solution you'd like**
The ability to flash an update to a single earbud as opposed to having to flash both at the same time.

**Additional context**
This fix would help with the longevity of galaxy buds, because as it stands now if one bud is lost or destroyed there is no way to pair a replacement bud unless both buds have matching firmware.

**Comment by ThePBone** [comment]
The latest release removed the battery check, so this issue should be resolved.
https://github.com/ThePBone/GalaxyBudsClient/releases
