### ISSUE TITLE
Buds 2 revision check

### ISSUE THREAD

**Issue by Mocar2D** [ThePBone/GalaxyBudsClient#474]
How do i find out what hardware revision my buds are or a better question for that would be, does installing different 'revision' update files for the buds change the hardware revision value to change? Or are these two (hardware revision, and firmware revision) not connected at all? And is there a way to check the hardware revision based of the serial number?

**Comment by ThePBone** [comment]
You can view your hardware revision by going to the system info in the app. It will display it there.

The firmware and hardware revision numbers are not connected at all.
The firmware revision just describes how often the firmware update was revised and sent to their internal QA team for testing. We only get to see the final revision of each firmware once it's released.
