### ISSUE TITLE
Any way to display temp in Fahrenheit instead of Celsius?

### ISSUE THREAD

**Issue by TGAMO** [ThePBone/GalaxyBudsClient#48]
Wow - really awesome little app - NICE!! Hate to bother you with such a trivial matter but i figured why not ask - Is it possible to have another slide switch or someway to display temp in F instead of C ?? Thank you!

**Comment by ThePBone** [comment]
Yes, you can click on the temperature value to toggle between Celsius and Fahrenheit.

**Comment by TGAMO** [comment]
GET THE FRIK OUTTA HERE!!!! SWEET!! - This is dashiznit! where is the donate page this is worth a pint on me bro! if you ever make it to the Big Easy hmu - we got some fishing to do.. lol
