### ISSUE TITLE
Received Corrupted data (Invalid SOM)

### ISSUE THREAD

**Issue by itsyecoder** [ThePBone/GalaxyBudsClient#49]
I am having an issue connecting these, the left earbud does not want to connect and I downloaded this program in hopes of getting it to work, but to no avail. Anyone know why my buds are doing this? Reddit post I put up here: https://www.reddit.com/r/galaxybuds/comments/jgtx6p/left_earbud_not_pairing_nor_charging/

**Comment by ArthurWolfhound** [comment]
That program is a replica of Samsung Wearable on Android, just built from scratch and code parts of original app by @ThePBone for Windows. I doubt anybody will be able to help you out. Github is a development service, not a forum - your best bet is to get official service...

**Comment by itsyecoder** [comment]
> That program is a replica of Samsung Wearable on Android, just built from scratch and code parts of original app by @ThePBone for Windows. I doubt anybody will be able to help you out. Github is a development service, not a forum - your best bet is to get official service...

I was wondering maybe the coders could give me some insight on what that code means.

**Comment by ThePBone** [comment]
`Received Corrupted data (Invalid SOM)` basically says that the manager is unable to find the start of a Bluetooth message within received binary data.

If you see that message, then at least one earbud appears to be connected to your computer, but it doesn't seem to respond correctly. However, I doubt that has something to do with your issue.

I'm not sure what caused your actual issue, but maybe your Buds are out of sync and require manual pairing. The Buds+ can be re-coupled by the user with no great difficulty. The original Buds, however, need to be re-coupled by Samsung's service center.
