### ISSUE TITLE
Android client? 

### ISSUE THREAD

**Issue by Salt505** [ThePBone/GalaxyBudsClient#50]
The official Samsung Galaxy Wearable app for Android asks for way too many permissions and has trackers. Is there any chance you would make an Android version of your open-source client?

**Comment by ThePBone** [comment]
Maybe yes, however only if it does not require many optimizations and can be compiled from the same sources as the desktop version.
I'm currently creating a Linux (and maybe macOS) port and I need to switch to a cross-platform UI .NET toolkit to make things work on non-Windows OSes.

This cross-platform UI toolkit has **very experimental** Android support, so it **may** be able to run that version on Android as well. If the UI toolkit properly works on Android then I could port the Linux version (when I finished it) without any big workarounds to Android. (Although that's rather low-priority for now.)

**Comment by Salt505** [comment]
> 
> 
> Maybe yes, however only if it does not require many optimizations and can be compiled from the same sources as the desktop version.
> I'm currently creating a Linux (and maybe macOS) port and I need to switch to a cross-platform UI .NET toolkit to make things work on non-Windows OSes.
> 
> This cross-platform UI toolkit has **very experimental** Android support, so it **may** be able to run that version on Android as well. If the UI toolkit properly works on Android then I could port the Linux version (when I finished it) without any big workarounds to Android. (Although that's rather low-priority for now.)

Thanks a ton for the reply! I'm sure a lot of people that value their privacy would love to have an Android client. I'll follow your work closely, thanks.

**Comment by Guiguim255** [comment]
Any update for a potential Android client ?
