### ISSUE TITLE
App does not start

### ISSUE THREAD

**Issue by idontknownl** [ThePBone/GalaxyBudsClient#55]
on Windws 10 build 19041.572 i cannot run the galaxy bud client anymore.
Even after removing the application and reinstalling it it does not work.

What I've noticed is that the SmartScreen prompt does not appear anymore when i try to launch the application

**Comment by ThePBone** [comment]
I recently received a few automated crash reports from this exact Windows version. I don't know if these crashes are related but it is very likely. 

Crash report: https://sentry.io/share/issue/f3ac4440ffd448219b8bf005d571ceeb/

According to the report, you are missing a dependency called "WindowsInput.dll". Could you check if it exists inside the installation folder (somewhere in program files).

**Comment by idontknownl** [comment]
it exists inside the installation folder.

**Comment by Xungerrrr** [comment]
Same issue on build 19042.610.

**Comment by idontknownl** [comment]
> I recently received a few automated crash reports from this exact Windows version. I don't know if these crashes are related but it is very likely.
> 
> Crash report: https://sentry.io/share/issue/f3ac4440ffd448219b8bf005d571ceeb/
> 
> According to the report, you are missing a dependency called "WindowsInput.dll". Could you check if it exists inside the installation folder (somewhere in program files)?

If there is anything i can test for you just let me know. I was thinking to reset my system, but now that someone else has confirmed the issue i will wait. As mentioned above the file that according to your crash report is actually in the folder.

**Comment by ThePBone** [comment]
You could try to delete all configuration data of the app:

1. Press Win+R
2. Copy `%localappdata%\ThePBone_(Tim_Schneeberge` into the text box of the Run dialog and hit enter
3. An explorer window should popup, you can delete all folders starting with "Galaxy_Buds_Client.exe_Url_"
4. Start the app again, maybe it'll work

**Comment by idontknownl** [comment]
it worked for me!

**Comment by ThePBone** [comment]
Nice! I think I found the issue that causes this problem. Apparently, the configuration storing I'm using was not thread-safe and created invalid config files in rare cases. It will be fixed in the next update.
