### ISSUE TITLE
GalaxyBudsManager does not get up

### ISSUE THREAD

**Issue by Buashei** [ThePBone/GalaxyBudsClient#59]
Hello.
I have a problem with GalaxyBudsManager, it has been working for a long time, I was even thinking about Polish translation.
Unfortunately, recently I had a problem with starting the application (I had to reset my computer / reinstall the application).
At this point, I am not able to run it.

![galaxybudsmanager](https://user-images.githubusercontent.com/46717105/99526647-d3804280-299b-11eb-9245-332ba51dce94.gif)

After "turn on" I can't see any instance of this app in task manager.

OS: Windows 10
Build: 10.0.18363
.NET: 4.6.1

**Comment by ThePBone** [comment]
Could you try to remove all configuration files for the app?
You can find instructions here: https://github.com/ThePBone/GalaxyBudsClient/issues/55#issuecomment-723158850

**Comment by Buashei** [comment]
@ThePBone Sorry for SPAM in issues, don't know why but I didn't see the #55  and I didn't even get the idea to clean the config. Thank you for your help
