### ISSUE TITLE
App not starting when clicked

### ISSUE THREAD

**Issue by skillz1925** [ThePBone/GalaxyBudsClient#64]
I click the app and it doesn't start. It seems like the issue from #55. I tried the thing you said to fix it and it didn't work.

**Comment by ArthurWolfhound** [comment]
Please do try to make these steps to get debug info, that is specific to your system:
1. Try to start application, and wait 30 seconds. Look at the time of start
2. Look into the event viewer (go to Windows Logs -> Applications and search for '.NET runtime')
3. Find those that concern GalaxyBudsManager and using Shift+Arrow Keys select those that fall into roughly +- 1 minute timeframe of you trying to launch the application
4. Right-click and "Save selected events"
5. In case of pop-up with, what language files should be included (possible on multi-language systems) select English
6. Select a place to save the evtx file. **Be aware that there will be additional folder with the same name that contains required resources!**
7. Get the evtx file and resource folder into zip-archive and post them here.

Please, keep in mind that developer is unable to treat such errors on case-to-case basis constantly, and there is a room for improvement in the future, but though your debug info now will be useful in diagnosing edge cases, there might not be an immediate response. Thank you for cooperation.

**Comment by skillz1925** [comment]
Thank you. Sorry it took so long to upload them.

[
[error.zip](https://github.com/ThePBone/GalaxyBudsClient/files/5625950/error.zip)

**Comment by skillz1925** [comment]
could it be that i didn't download the net framework before updating the app?

**Comment by ThePBone** [comment]
According to the error dump, it looks like your configuration files are corrupted and do not contain valid XML data.

Error stacktraces:
```
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[])
   at System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   [...]

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   [...]
```
 
To fix this you need to [remove all configuration files](https://github.com/ThePBone/GalaxyBudsClient/issues/55#issuecomment-723158850) for this app.
I know you are already said you tried the fix, but the configuration module still reads some file, so there must still be one broken file somewhere.

**Comment by skillz1925** [comment]
i deleted the user config file in that folder and it worked. Thank you!
