### ISSUE TITLE
(REQ) Gaming mode - Windos 10 app - Galaxy buds plus

### ISSUE THREAD

**Issue by Ric638** [ThePBone/GalaxyBudsClient#90]
Hello.
I own Samsung Galaxy Buds Plus earbuds and use them to listen to Netflix on my Dell Lattitude 5285 tablet - (Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz   2.90 GHz -  16GB Ram. - Windows 10 pro 64bits).
I would love to have a Windows App to be able to turn on Gaming mode on my Earbuds, thus eliminating the latency problem (Sound not quit synced with video)

Thanks alot for your work.

Eric C

**Comment by ThePBone** [comment]
Unfortunately, this is not possible without the help of Samsung. Gaming mode requires a special proprietary Bluetooth codec (SSC) made by Samsung. This codec is only available for Samsung Android devices running OneUI and can't be ported to any other platform unless Samsung themselves decide to do so.
Even though this will probably never happen, if they open-source their codec or release a Windows driver for it, I could see Gaming mode functionality on Windows.

There's also the possibility of reverse-engineering the encoder binaries from Samsung's OneUI. Still, it contains loads of complicated algorithms, so this procedure would take a huge amount of time and is not an option.
