### ISSUE TITLE
[BUG] Program closes automatically when is in tray mode

### ISSUE THREAD

**Issue by giovanniro98** [ThePBone/GalaxyBudsClient#91]
Windows 10 64bit
After some time in the system tray the program closes automatically and the icon disappear (I can't find it running in the task manager also).
Latest downloadable version.

**Comment by ThePBone** [comment]
It is very likely that the app crashed in the background while handling a connection change of your earbuds. I've received a few automated crash reports showing that the problem is an unhandled error in the Bluetooth backend. I'll look at it later.

**Comment by giovanniro98** [comment]
Yes, it's probabily as you said because when the earbuds are disconnected the program stay up and running just fine.

**Comment by ThePBone** [comment]
I fixed that. I'm now nearly any error in the connect/send/receive routines of the Bluetooth backend.

Windows binaries are still compiling atm but you can get updated binaries from the latest workflow: https://github.com/ThePBone/GalaxyBudsClient/actions?query=workflow%3A%22Compile+Windows+binaries%22
